/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author darie
 */
public class FmrUsuarios extends javax.swing.JInternalFrame {

        private conexion conClase = new conexion();
    /**
     * Creates new form FmrUsuarios
     */
    public FmrUsuarios() {
        initComponents();
        configurarEstructuraInicial();
        mostrarTabla("");
        configurarEventosManuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jLabelEstadoC = new javax.swing.JLabel();
        jLabelGESTIÓN = new javax.swing.JLabel();
        jLabelIdUsuario = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNombreU = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNUR = new javax.swing.JTable();
        jLabelTotalU = new javax.swing.JLabel();
        jLabelNusuario = new javax.swing.JLabel();

        jLabelContraseña.setText("Contraseña *:");

        jLabelRol.setText("Rol de Sistema *:");

        jLabelEstadoC.setText("Estado Cuenta *:");

        jLabelGESTIÓN.setText("👥 GESTIÓN DE USUARIOS Y CONTROL DE ACCESOS (SISTEMA CARNICERÍA)");

        jLabelIdUsuario.setText("ID Usuario:");

        jLabelNombre.setText("Nombre Completo *:");

        jLabelNombreU.setText("Nombre Usuario *");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(this::jButtonGuardarActionPerformed);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(this::jButtonEditarActionPerformed);

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(this::jButtonLimpiarActionPerformed);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(this::jButtonSalirActionPerformed);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jPasswordField1.addActionListener(this::jPasswordField1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        jLabelBuscar.setText("Buscar (Nombre/Usuario):");

        jTextFieldBuscar.addActionListener(this::jTextFieldBuscarActionPerformed);

        jTableNUR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Completo", "Usuario", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNUR);

        jLabelTotalU.setText("Total Usuarios:");

        jLabelNusuario.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonGuardar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelGESTIÓN)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIdUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombreU)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelContraseña)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelRol)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelEstadoC)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBuscar)
                        .addGap(34, 34, 34)
                        .addComponent(jTextFieldBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelTotalU)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelNusuario))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGESTIÓN)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdUsuario)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreU)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelContraseña)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRol)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstadoC)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalU)
                    .addComponent(jLabelNusuario))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void configurarEstructuraInicial() {
        jTextField1.setEnabled(false); 
        
        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Jefe", "Empleado" }));
        jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
    }
    
    private void configurarEventosManuales() {
        // 🔍 Filtro dinámico en tiempo real
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mostrarTabla(jTextFieldBuscar.getText().trim());
            }
        });

        // 鼠标 Al hacer clic en la tabla se mapean los datos a las cajas de texto y combos
        jTableNUR.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = jTableNUR.getSelectedRow();
                if (fila >= 0) {
                    Object idVal = jTableNUR.getValueAt(fila, 0);
                    Object nomVal = jTableNUR.getValueAt(fila, 1);
                    Object usuVal = jTableNUR.getValueAt(fila, 2);
                    Object rolVal = jTableNUR.getValueAt(fila, 3);
                    Object estVal = jTableNUR.getValueAt(fila, 4);
                    
                    if (idVal != null) jTextField1.setText(idVal.toString());
                    if (nomVal != null) jTextField2.setText(nomVal.toString());
                    if (usuVal != null) jTextField3.setText(usuVal.toString());
                    
                    if (rolVal != null) jComboBox1.setSelectedItem(rolVal.toString());
                    if (estVal != null) jComboBox2.setSelectedItem(estVal.toString());
                    
                    jPasswordField1.setText(""); // Por seguridad se limpia el password
                }
            }
        });
    }
    
    public void mostrarTabla(String valorBuscar) {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Nombre Completo", "Usuario", "Rol", "Estado"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        jTableNUR.setModel(modelo);
        modelo.setRowCount(0);
        
        String sql = "SELECT u.id_usuario, u.nombre, u.usuario, r.nombre_rol, u.estado "
                   + "FROM usuarios u "
                   + "INNER JOIN roles r ON u.id_rol = r.id_rol "
                   + "WHERE u.nombre LIKE ? OR u.usuario LIKE ? "
                   + "ORDER BY u.id_usuario DESC";
        
        int totalUsuarios = 0;
        
        // Se instancia la clase local directamente en el try-with-resources sin guardarla en propiedad
        try (Connection con = new conexion().conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            if (con == null) return;
            
            ps.setString(1, "%" + valorBuscar.trim() + "%");
            ps.setString(2, "%" + valorBuscar.trim() + "%");
            
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    modelo.addRow(new Object[]{
                        rs.getInt("id_usuario"),
                        rs.getString("nombre"),
                        rs.getString("usuario"),
                        rs.getString("nombre_rol"),
                        rs.getString("estado")
                    });
                    totalUsuarios++;
                }
            }
            
            jLabelNusuario.setText(String.valueOf(totalUsuarios));
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de usuarios: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Limpia todos los controles del formulario
     */
    private void limpiarCampos() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jPasswordField1.setText("");
        jTextFieldBuscar.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTableNUR.clearSelection();
    }

    /**
     * Obtiene el ID numérico del Rol basándose en su nombre de la base de datos
     */
    private int obtenerIdRol(String nombreRol) {
        String sql = "SELECT id_rol FROM roles WHERE nombre_rol = ?";
        // Se invoca directamente la clase conexion
        try (Connection con = new conexion().conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, nombreRol);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("id_rol");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al obtener ID del rol: " + e.getMessage());
        }
        return 2; 
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

String nombre = jTextField2.getText().trim();
        String usuario = jTextField3.getText().trim();
        String clave = new String(jPasswordField1.getPassword()).trim();
        String rolSeleccionado = jComboBox1.getSelectedItem().toString();
        String estado = jComboBox2.getSelectedItem().toString();

        if (nombre.isEmpty() || usuario.isEmpty() || clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios (*)", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idRol = obtenerIdRol(rolSeleccionado);
        String sql = "INSERT INTO usuarios (nombre, usuario, clave, id_rol, estado) VALUES (?, ?, ?, ?, ?)";

        try (Connection con = new conexion().conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            if (con == null) return;
            ps.setString(1, nombre);
            ps.setString(2, usuario);
            ps.setString(3, clave);
            ps.setInt(4, idRol);
            ps.setString(5, estado);

            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.");
                jButtonLimpiarActionPerformed(null); 
            }
        } catch (SQLException e) {
            if (e.getErrorCode() == 1062) { 
                JOptionPane.showMessageDialog(this, "El nombre de usuario '" + usuario + "' ya se encuentra registrado.", "Usuario Duplicado", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el usuario: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

String idUsuario = jTextField1.getText().trim();
        String nombre = jTextField2.getText().trim();
        String usuario = jTextField3.getText().trim();
        String clave = new String(jPasswordField1.getPassword()).trim();
        String rolSeleccionado = jComboBox1.getSelectedItem().toString();
        String estado = jComboBox2.getSelectedItem().toString();

        if (idUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla para editar.", "Selección Requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (nombre.isEmpty() || usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre y el usuario no pueden quedar vacíos.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idRol = obtenerIdRol(rolSeleccionado);
        
        String sql;
        if (clave.isEmpty()) {
            sql = "UPDATE usuarios SET nombre = ?, usuario = ?, id_rol = ?, estado = ? WHERE id_usuario = ?";
        } else {
            sql = "UPDATE usuarios SET nombre = ?, usuario = ?, clave = ?, id_rol = ?, estado = ? WHERE id_usuario = ?";
        }

        try (Connection con = new conexion().conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            if (con == null) return;
            ps.setString(1, nombre);
            ps.setString(2, usuario);
            
            if (clave.isEmpty()) {
                ps.setInt(3, idRol);
                ps.setString(4, estado);
                ps.setInt(5, Integer.parseInt(idUsuario));
            } else {
                ps.setString(3, clave);
                ps.setInt(4, idRol);
                ps.setString(5, estado);
                ps.setInt(6, Integer.parseInt(idUsuario));
            }

            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
                jButtonLimpiarActionPerformed(null); 
            }
        } catch (SQLException e) {
            if (e.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(this, "El nombre de usuario '" + usuario + "' ya pertenece a otra cuenta.", "Usuario Duplicado", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el usuario: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiarCampos();
        mostrarTabla(""); 
        jTextField2.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
  dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
   mostrarTabla(jTextFieldBuscar.getText().trim());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelEstadoC;
    private javax.swing.JLabel jLabelGESTIÓN;
    private javax.swing.JLabel jLabelIdUsuario;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreU;
    private javax.swing.JLabel jLabelNusuario;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTotalU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNUR;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
