/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author darie
 */
public class FrmCategorias extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCategorias
     */
    public FrmCategorias() {
        initComponents();
        jTextFieldIdcategoria.setEnabled(false); 
        
        // Cargar los datos en la JTable al abrir la interfaz
        mostrarCategorias("");
        
        // Asignar los listeners manuales que faltan del diseño dinámico
        configurarEventosManuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelGESTIÓNDECATEGORÍASDEPRODUCTOS = new javax.swing.JLabel();
        jLabelIdcategoria = new javax.swing.JLabel();
        jLabelNombredelaCategoría = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jLabelBCategoria = new javax.swing.JLabel();
        jTextFieldIdcategoria = new javax.swing.JTextField();
        jTextFieldNdeCategoria = new javax.swing.JTextField();
        jTextFieldBCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTCategoria = new javax.swing.JTable();
        jButtonSalir = new javax.swing.JButton();

        jLabelGESTIÓNDECATEGORÍASDEPRODUCTOS.setText("📂 GESTIÓN DE CATEGORÍAS DE PRODUCTOS");

        jLabelIdcategoria.setText("ID Categoría (Auto):");

        jLabelNombredelaCategoría.setText("Nombre de la Categoría:");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(this::jButtonGuardarActionPerformed);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(this::jButtonEditarActionPerformed);

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(this::jButtonLimpiarActionPerformed);

        jLabelBCategoria.setText("Buscar Categoría:");

        jTextFieldIdcategoria.addActionListener(this::jTextFieldIdcategoriaActionPerformed);

        jTextFieldNdeCategoria.addActionListener(this::jTextFieldNdeCategoriaActionPerformed);

        jTextFieldBCategoria.addActionListener(this::jTextFieldBCategoriaActionPerformed);

        jTableTCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Categoría", "Nombre de la Categoría"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTCategoria);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(this::jButtonSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGESTIÓNDECATEGORÍASDEPRODUCTOS)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIdcategoria)
                                    .addComponent(jLabelNombredelaCategoría))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIdcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNdeCategoria)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonGuardar)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSalir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpiar)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelBCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBCategoria))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGESTIÓNDECATEGORÍASDEPRODUCTOS)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdcategoria)
                    .addComponent(jLabelBCategoria)
                    .addComponent(jTextFieldIdcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombredelaCategoría)
                    .addComponent(jTextFieldNdeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardar)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonLimpiar))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarCategorias(String valor) {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"ID Categoría", "Nombre de la Categoría"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Garantiza que la JTable sea de SOLO LECTURA
            }
        };
        jTableTCategoria.setModel(modelo);
        modelo.setRowCount(0); 

        String sql = "SELECT id_categoria, nombre_categoria FROM categorias WHERE nombre_categoria LIKE ? ORDER BY id_categoria DESC";
        conexion conClase = new conexion();

        try (Connection con = conClase.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            if (con == null) return;

            ps.setString(1, "%" + valor.trim() + "%");

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    modelo.addRow(new Object[]{
                        rs.getInt("id_categoria"),
                        rs.getString("nombre_categoria")
                    });
                }
            }
        } catch (Exception e) {
            System.err.println("Error al mapear categorías en la tabla: " + e.getMessage());
        }
    }
    
    private void configurarEventosManuales() {
        // 🔍 Buscador en tiempo real por cada tecla soltada
        jTextFieldBCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mostrarCategorias(jTextFieldBCategoria.getText().trim());
            }
        });

        // 🖱️ Clic en la tabla para transferir datos a los campos superiores
        jTableTCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = jTableTCategoria.getSelectedRow();
                if (fila >= 0) {
                    Object idVal = jTableTCategoria.getValueAt(fila, 0);
                    Object nomVal = jTableTCategoria.getValueAt(fila, 1);
                    
                    if (idVal != null && nomVal != null) {
                        jTextFieldIdcategoria.setText(idVal.toString());
                        jTextFieldNdeCategoria.setText(nomVal.toString());
                    }
                }
            }
        });
    }
    
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
       dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
    String nombre = jTextFieldNdeCategoria.getText().trim();
        
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la categoría es obligatorio.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO categorias (nombre_categoria) VALUES (?)";
        conexion conClase = new conexion();
        
        try (Connection con = conClase.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            if (con == null) return;
            ps.setString(1, nombre);
            
            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "¡Categoría registrada con éxito!");
                jButtonLimpiarActionPerformed(null); // Borra campos y recarga la tabla automáticamente
            }
            
        } catch (SQLException e) {
            if (e.getErrorCode() == 1062) { // Llave única duplicada en MariaDB
                JOptionPane.showMessageDialog(this, "Error: La categoría '" + nombre + "' ya existe.", "Duplicado", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
        }    
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        String idStr = jTextFieldIdcategoria.getText().trim();
        String nombre = jTextFieldNdeCategoria.getText().trim();
        
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona primero una categoría de la tabla para poder editarla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la categoría no puede estar vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "UPDATE categorias SET nombre_categoria = ? WHERE id_categoria = ?";
        conexion conClase = new conexion();
        
        try (Connection con = conClase.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            if (con == null) return;
            ps.setString(1, nombre);
            ps.setInt(2, Integer.parseInt(idStr));
            
            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Categoría actualizada correctamente.");
                jButtonLimpiarActionPerformed(null); // Refresca y limpia la pantalla
            }
        } catch (SQLException e) {
            if (e.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(this, "Error: Ya existe otra categoría con el nombre '" + nombre + "'.", "Duplicado", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
    jTextFieldIdcategoria.setText("");
        jTextFieldNdeCategoria.setText("");
        jTextFieldBCategoria.setText("");
        
        mostrarCategorias(""); // Restablece la tabla completa
        jTextFieldNdeCategoria.requestFocus(); // Pone el cursor listo para escribir
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextFieldBCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBCategoriaActionPerformed

    private void jTextFieldIdcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdcategoriaActionPerformed

    private void jTextFieldNdeCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNdeCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNdeCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBCategoria;
    private javax.swing.JLabel jLabelGESTIÓNDECATEGORÍASDEPRODUCTOS;
    private javax.swing.JLabel jLabelIdcategoria;
    private javax.swing.JLabel jLabelNombredelaCategoría;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTCategoria;
    private javax.swing.JTextField jTextFieldBCategoria;
    private javax.swing.JTextField jTextFieldIdcategoria;
    private javax.swing.JTextField jTextFieldNdeCategoria;
    // End of variables declaration//GEN-END:variables
}
