/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author darie
 */
public class FrmCompras extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloDetalle;
    private double totalCompra = 0.0;
    
    
    /**
     * Creates new form FrmCompras
     */
    public FrmCompras() {
        initComponents();
        inicializarLogicaYEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRCompras = new javax.swing.JLabel();
        jLabelProveedor = new javax.swing.JLabel();
        jLabelAgregarP = new javax.swing.JLabel();
        jLabelCódigoBarras = new javax.swing.JLabel();
        jLabelCantidadKG = new javax.swing.JLabel();
        jComboBoxProveedor = new javax.swing.JComboBox<>();
        jTextFieldCódigoBarras = new javax.swing.JTextField();
        jTextFieldCantidadKG = new javax.swing.JTextField();
        jLabelProducto = new javax.swing.JLabel();
        jLabelNameProducto = new javax.swing.JLabel();
        jLabelCosto = new javax.swing.JLabel();
        jTextFieldCosto = new javax.swing.JTextField();
        jButtonAgregaralDetalle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCPCPS = new javax.swing.JTable();
        jButtonProcesarCompras = new javax.swing.JButton();
        jButtonQuitarItem = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelTOTAL = new javax.swing.JLabel();
        jLabelNtOTAL = new javax.swing.JLabel();

        jLabelRCompras.setText("REGISTRO DE COMPRAS DE MERCANCÍA");

        jLabelProveedor.setText("Proveedor:");

        jLabelAgregarP.setText("Agregar Producto");

        jLabelCódigoBarras.setText("Código Barras:");

        jLabelCantidadKG.setText("Cantidad (KG):");

        jComboBoxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxProveedor.addActionListener(this::jComboBoxProveedorActionPerformed);

        jTextFieldCódigoBarras.addActionListener(this::jTextFieldCódigoBarrasActionPerformed);

        jTextFieldCantidadKG.addActionListener(this::jTextFieldCantidadKGActionPerformed);

        jLabelProducto.setText("Producto:");

        jLabelNameProducto.setText("`CARNE`");

        jLabelCosto.setText("Costo x KG ($):");

        jTextFieldCosto.addActionListener(this::jTextFieldCostoActionPerformed);

        jButtonAgregaralDetalle.setText("Agregar al Detalle");
        jButtonAgregaralDetalle.addActionListener(this::jButtonAgregaralDetalleActionPerformed);

        jTableCPCPS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Cantidad (KG)", "Precio Compra", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCPCPS);

        jButtonProcesarCompras.setText("Procesar Compra");
        jButtonProcesarCompras.addActionListener(this::jButtonProcesarComprasActionPerformed);

        jButtonQuitarItem.setText("Quitar Item");
        jButtonQuitarItem.addActionListener(this::jButtonQuitarItemActionPerformed);

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(this::jButtonLimpiarActionPerformed);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(this::jButtonSalirActionPerformed);

        jLabelTOTAL.setText("TOTAL:");

        jLabelNtOTAL.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRCompras)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelAgregarP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelCantidadKG)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCantidadKG, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelCódigoBarras)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCódigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelProducto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelNameProducto))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelCosto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCosto))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonProcesarCompras)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonQuitarItem)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabelTOTAL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNtOTAL)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAgregaralDetalle)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRCompras)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProveedor)
                    .addComponent(jComboBoxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabelAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCódigoBarras)
                    .addComponent(jTextFieldCódigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProducto)
                    .addComponent(jLabelNameProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidadKG)
                    .addComponent(jTextFieldCantidadKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCosto)
                    .addComponent(jTextFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregaralDetalle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTOTAL)
                        .addComponent(jLabelNtOTAL))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonProcesarCompras)
                        .addComponent(jButtonQuitarItem)
                        .addComponent(jButtonLimpiar)
                        .addComponent(jButtonSalir)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarLogicaYEventos() {
    // Inicializar el modelo dinámico sobre tu tabla jTableCPCPS
    modeloDetalle = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Código", "Producto", "Cantidad (KG)", "Precio Compra", "Subtotal"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    jTableCPCPS.setModel(modeloDetalle);

    // Limpiar labels por defecto
    jLabelNameProducto.setText("---");
    jLabelNtOTAL.setText("0.00");

    // 1. CONFIGURACIÓN DEL COMBOBOX DE PROVEEDORES COMO BUSCADOR
    jComboBoxProveedor.setEditable(true); // Permitir escribir adentro
    configurarBuscadorProveedores();

    // 2. CONFIGURACIÓN DE LOS EVENTOS DE BÚSQUEDA DE PRODUCTO
    // Buscar por ENTER en código de barras
    jTextFieldCódigoBarras.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buscarProductoPorCodigo();
        }
    });

    
    
    // Buscar por ENTER escribiendo en el label/campo del producto (Abrirá ventana si no hay código)
    // Para facilitar esto, usaremos un truco intuitivo: si presionan ENTER con el código vacío, abre el buscador.
}
    
   private void buscarProductoPorCodigo() {
    String entrada = jTextFieldCódigoBarras.getText().trim();
    
    // Si el campo está vacío, asumimos que quiere buscar por nombre de producto
    if (entrada.isEmpty()) {
        String busquedaNombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del producto a buscar:", "Buscador de Productos", JOptionPane.QUESTION_MESSAGE);
        if (busquedaNombre == null || busquedaNombre.trim().isEmpty()) return;
        entrada = busquedaNombre.trim();
    }

    // Primero intentamos buscar de forma exacta por código de barras
    String sql = "SELECT codigo_barras, nombre FROM productos WHERE codigo_barras = ? AND estado = 'Activo'";
    try (Connection con = new conexion().conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, entrada);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                jTextFieldCódigoBarras.setText(rs.getString("codigo_barras"));
                jLabelNameProducto.setText(rs.getString("nombre"));
                jTextFieldCantidadKG.requestFocus();
                return; // Encontrado con éxito
            }
        }
    } catch (SQLException e) {
        System.err.println("Error: " + e.getMessage());
    }

    // Si no se encontró por código exacto, realizamos una búsqueda inteligente por coincidencia de nombre
    String sqlLike = "SELECT codigo_barras, nombre, precio_kg FROM productos WHERE nombre LIKE ? AND estado = 'Activo' ORDER BY nombre ASC";
    try (Connection con = new conexion().conectar();
         PreparedStatement ps = con.prepareStatement(sqlLike)) {
        ps.setString(1, "%" + entrada + "%");
        
        try (ResultSet rs = ps.executeQuery()) {
            java.util.List<String> opciones = new java.util.ArrayList<>();
            java.util.List<String> codigos = new java.util.ArrayList<>();
            
            while (rs.next()) {
                codigos.add(rs.getString("codigo_barras"));
                opciones.add(rs.getString("nombre") + " [" + rs.getString("codigo_barras") + "]");
            }
            
            if (opciones.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron productos con ese código o nombre.", "Sin resultados", JOptionPane.WARNING_MESSAGE);
                jLabelNameProducto.setText("---");
            } else if (opciones.size() == 1) {
                // Si solo hay una coincidencia, la selecciona automáticamente
                jTextFieldCódigoBarras.setText(codigos.get(0));
                jLabelNameProducto.setText(opciones.get(0).split(" \\[")[0]);
                jTextFieldCantidadKG.requestFocus();
            } else {
                // Si hay múltiples coincidencias, le despliega una lista limpia para elegir el correcto
                String seleccion = (String) JOptionPane.showInputDialog(
                    this, 
                    "Seleccione el producto exacto:", 
                    "Múltiples Coincidencias Encontradas", 
                    JOptionPane.PLAIN_MESSAGE, 
                    null, 
                    opciones.toArray(), 
                    opciones.get(0)
                );
                
                if (seleccion != null) {
                    int index = opciones.indexOf(seleccion);
                    jTextFieldCódigoBarras.setText(codigos.get(index));
                    jLabelNameProducto.setText(seleccion.split(" \\[")[0]);
                    jTextFieldCantidadKG.requestFocus();
                }
            }
        }
    } catch (SQLException e) {
        System.err.println("Error en búsqueda por nombre: " + e.getMessage());
    }
}

    private int obtenerIdProveedor(String nombreProv) {
        String sql = "SELECT id_proveedor FROM proveedores WHERE nombre = ?";
        try (Connection con = new conexion().conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, nombreProv);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return rs.getInt("id_proveedor");
            }
        } catch (SQLException e) {
            System.err.println("Error al obtener ID del proveedor: " + e.getMessage());
        }
        return 1; 
    }

    private void calcularTotal() {
        totalCompra = 0.0;
        for (int i = 0; i < modeloDetalle.getRowCount(); i++) {
            totalCompra += (double) modeloDetalle.getValueAt(i, 4);
        }
        jLabelNtOTAL.setText(String.format("%.2f", totalCompra));
    }

    private void limpiarFormulario() {
        modeloDetalle.setRowCount(0);
        jTextFieldCódigoBarras.setText("");
        jLabelNameProducto.setText("---");
        jTextFieldCantidadKG.setText("");
        jTextFieldCosto.setText("");
        jLabelNtOTAL.setText("0.00");
        totalCompra = 0.0;
        if (jComboBoxProveedor.getItemCount() > 0) jComboBoxProveedor.setSelectedIndex(0);
        jTextFieldCódigoBarras.requestFocus();
    }
    
    private void jTextFieldCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostoActionPerformed

    private void jComboBoxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProveedorActionPerformed

    private void jTextFieldCódigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCódigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCódigoBarrasActionPerformed

    private void jTextFieldCantidadKGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadKGActionPerformed

    private void jButtonProcesarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarComprasActionPerformed

if (jTableCPCPS.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "El detalle de la compra está vacío.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String provSel = jComboBoxProveedor.getSelectedItem() != null ? jComboBoxProveedor.getSelectedItem().toString() : "Proveedor Genérico";
        int idProveedor = obtenerIdProveedor(provSel);

        Connection con = null;
        PreparedStatement psCompra = null;
        PreparedStatement psDetalle = null;
        PreparedStatement psStock = null;

        try {
            con = new conexion().conectar();
            con.setAutoCommit(false); // Transacción segura

            // 1. Cabecera
            String sqlCompra = "INSERT INTO compras (id_proveedor, fecha, total) VALUES (?, NOW(), ?)";
            psCompra = con.prepareStatement(sqlCompra, Statement.RETURN_GENERATED_KEYS);
            psCompra.setInt(1, idProveedor);
            psCompra.setDouble(2, totalCompra);
            psCompra.executeUpdate();

            int idCompra = 1;
            try (ResultSet gk = psCompra.getGeneratedKeys()) {
                if (gk.next()) idCompra = gk.getInt(1);
            }

            // 2. Lotes de Detalles y Stock
            String sqlDetalle = "INSERT INTO detalle_compras (id_compra, codigo_barras, cantidad_kg, precio_compra) VALUES (?, ?, ?, ?)";
            String sqlStock = "UPDATE productos SET stock_kg = stock_kg + ? WHERE codigo_barras = ?";

            psDetalle = con.prepareStatement(sqlDetalle);
            psStock = con.prepareStatement(sqlStock);

            for (int i = 0; i < jTableCPCPS.getRowCount(); i++) {
                String cod = jTableCPCPS.getValueAt(i, 0).toString();
                double cant = (double) jTableCPCPS.getValueAt(i, 2);
                double cost = (double) jTableCPCPS.getValueAt(i, 3);

                psDetalle.setInt(1, idCompra);
                psDetalle.setString(2, cod);
                psDetalle.setDouble(3, cant);
                psDetalle.setDouble(4, cost);
                psDetalle.addBatch();

                psStock.setDouble(1, cant);
                psStock.setString(2, cod);
                psStock.addBatch();
            }

            psDetalle.executeBatch();
            psStock.executeBatch();

            con.commit();
            JOptionPane.showMessageDialog(this, "Compra registrada. Inventario actualizado.");
            limpiarFormulario();

        } catch (SQLException e) {
            if (con != null) {
                try { con.rollback(); } catch (SQLException ex) { System.err.println(ex.getMessage()); }
            }
            JOptionPane.showMessageDialog(this, "Error al procesar: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (psCompra != null) psCompra.close();
                if (psDetalle != null) psDetalle.close();
                if (psStock != null) psStock.close();
                if (con != null) con.close();
            } catch (SQLException e) { System.err.println(e.getMessage()); }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProcesarComprasActionPerformed

    private void jButtonAgregaralDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregaralDetalleActionPerformed

String codigo = jTextFieldCódigoBarras.getText().trim();
        String nombre = jLabelNameProducto.getText();
        String cantStr = jTextFieldCantidadKG.getText().trim();
        String costStr = jTextFieldCosto.getText().trim();

        if (codigo.isEmpty() || nombre.equals("---") || cantStr.isEmpty() || costStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe buscar un producto válido, ingresar cantidad y costo.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double cantidad = Double.parseDouble(cantStr);
            double costo = Double.parseDouble(costStr);
            double subtotal = cantidad * costo;

            // Agrupar filas del mismo código de producto si ya existe en la tabla
            for (int i = 0; i < jTableCPCPS.getRowCount(); i++) {
                if (jTableCPCPS.getValueAt(i, 0).toString().equals(codigo)) {
                    double cantExistente = (double) jTableCPCPS.getValueAt(i, 2);
                    double nuevoSubtotal = (cantExistente + cantidad) * costo;
                    jTableCPCPS.setValueAt(cantExistente + cantidad, i, 2);
                    jTableCPCPS.setValueAt(costo, i, 3);
                    jTableCPCPS.setValueAt(nuevoSubtotal, i, 4);
                    calcularTotal();
                    
                    // Reset parcial para nueva inserción
                    jTextFieldCódigoBarras.setText("");
                    jLabelNameProducto.setText("---");
                    jTextFieldCantidadKG.setText("");
                    jTextFieldCosto.setText("");
                    jTextFieldCódigoBarras.requestFocus();
                    return;
                }
            }

            // Añadir fila nueva
            modeloDetalle.addRow(new Object[]{codigo, nombre, cantidad, costo, subtotal});
            calcularTotal();

            // Reset parcial
            jTextFieldCódigoBarras.setText("");
            jLabelNameProducto.setText("---");
            jTextFieldCantidadKG.setText("");
            jTextFieldCosto.setText("");
            jTextFieldCódigoBarras.requestFocus();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese números válidos para cantidad y costo.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregaralDetalleActionPerformed

    private void jButtonQuitarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarItemActionPerformed

int fila = jTableCPCPS.getSelectedRow();
        if (fila >= 0) {
            modeloDetalle.removeRow(fila);
            calcularTotal();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla para quitarlo.", "Atención", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuitarItemActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
   
// ELIMINADO: modeloDetalle.setRowCount(0); <-- Ya no limpia la tabla, se usa Quitar Item
    jTextFieldCódigoBarras.setText("");
    jLabelNameProducto.setText("---");
    jTextFieldCantidadKG.setText("");
    jTextFieldCosto.setText("");
    
    // Mantiene el foco listo para ingresar otro producto a la misma compra
    jTextFieldCódigoBarras.requestFocus();      

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
     
    dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregaralDetalle;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonProcesarCompras;
    private javax.swing.JButton jButtonQuitarItem;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxProveedor;
    private javax.swing.JLabel jLabelAgregarP;
    private javax.swing.JLabel jLabelCantidadKG;
    private javax.swing.JLabel jLabelCosto;
    private javax.swing.JLabel jLabelCódigoBarras;
    private javax.swing.JLabel jLabelNameProducto;
    private javax.swing.JLabel jLabelNtOTAL;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelRCompras;
    private javax.swing.JLabel jLabelTOTAL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCPCPS;
    private javax.swing.JTextField jTextFieldCantidadKG;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldCódigoBarras;
    // End of variables declaration//GEN-END:variables

    private void configurarBuscadorProveedores() {
      
        jComboBoxProveedor.removeAllItems();
    // Ajustado a tu columna real 'nombre_empresa' de la tabla 'proveedores'
    String sqlProv = "SELECT nombre_empresa FROM proveedores ORDER BY nombre_empresa ASC";
    try (Connection con = new conexion().conectar();
         PreparedStatement ps = con.prepareStatement(sqlProv);
         ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            jComboBoxProveedor.addItem(rs.getString("nombre_empresa"));
        }
    } catch (SQLException e) {
        System.err.println("Error al cargar proveedores: " + e.getMessage());
        jComboBoxProveedor.addItem("Proveedor Genérico");
    }

    // Configurar autocompletado interactivo al escribir
    final javax.swing.JTextField tf = (javax.swing.JTextField) jComboBoxProveedor.getEditor().getEditorComponent();
    tf.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent e) {
            // Evitar interceptar flechas de navegación
            if (e.getKeyCode() == java.awt.event.KeyEvent.VK_UP || 
                e.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN || 
                e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                return;
            }
            
            String texto = tf.getText();
            jComboBoxProveedor.removeAllItems();
            
            String sqlFiltrar = "SELECT nombre_empresa FROM proveedores WHERE nombre_empresa LIKE ? ORDER BY nombre_empresa ASC";
            try (Connection con = new conexion().conectar();
                 PreparedStatement ps = con.prepareStatement(sqlFiltrar)) {
                ps.setString(1, "%" + texto + "%");
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        jComboBoxProveedor.addItem(rs.getString("nombre_empresa"));
                    }
                }
            } catch (SQLException ex) {
                System.err.println(ex.getMessage());
            }
            tf.setText(texto);
            jComboBoxProveedor.showPopup();
        }
    });
        
    }
}
