/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author darie
 */
public class FrmClientes extends javax.swing.JInternalFrame {

    private int idCliente;

    /**
     * Creates new form Frmlak
     */
    public FrmClientes() {
        initComponents();
        
        // 🔥 Hace que los clientes y el contador carguen automáticamente al abrir la ventana
        mostrarClientes(""); 
        
        // 🖱️ Al hacer clic en una fila de la tabla, los datos cargan en las casillas para editar/eliminar
        // 🖱️ Al hacer clic en una fila de la tabla, los datos cargan en las casillas para editar/eliminar
jTableclientes.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int fila = jTableclientes.getSelectedRow();
        if (fila >= 0) {
            // 🛡️ Validamos que la celda de la cédula no esté vacía o sea nula
            Object valorCedula = jTableclientes.getValueAt(fila, 0);
            if (valorCedula == null || valorCedula.toString().trim().isEmpty()) {
                return; // Si está vacía (fila por defecto), no hace nada y evita el error
            }
            
            String cedulaSeleccionada = valorCedula.toString().trim();
            
            String sql = "SELECT * FROM clientes WHERE cedula = ?";
            conexion conClase = new conexion();
            try (Connection con = conClase.conectar();
                 PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setString(1, cedulaSeleccionada);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        jTextFieldCedula.setText(rs.getString("cedula"));
                        
                        // Reconstruir nombres y apellidos
                        String nombreCompleto = (rs.getString("nombre") + " " + (rs.getString("segundo_nombre") != null ? rs.getString("segundo_nombre") : "")).trim();
                        String apellidoCompleto = (rs.getString("apellido") + " " + (rs.getString("segundo_apellido") != null ? rs.getString("segundo_apellido") : "")).trim();
                        
                        jTextFieldNombre.setText(nombreCompleto);
                        jTextFieldApellido.setText(apellidoCompleto);
                        jTextFieldTelefono.setText(rs.getString("telefono"));
                        jTextFieldDireccion.setText(rs.getString("direccion"));
                    }
                }
            } catch (Exception e) {
                System.err.println("Error al cargar cliente desde la tabla: " + e.getMessage());
            }
        }
    }
});

// 🔍 Evento para que la tabla se actualice en tiempo real al escribir o borrar
jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyReleased(java.awt.event.KeyEvent evt) {
        String textoBusqueda = jTextFieldBuscar.getText().trim();
        
        // Si el usuario borró todo y quedó vacío, limpia el filtro y muestra todos
        if (textoBusqueda.isEmpty()) {
            mostrarClientes(""); 
        } else {
            // Si hay texto, busca el cliente específico
            mostrarClientes(textoBusqueda);
        }
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelMÓDULODECLIENTES = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabelBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableclientes = new javax.swing.JTable();
        jLabelClientesR = new javax.swing.JLabel();
        jLabelNClientesR = new javax.swing.JLabel();
        jButtonSalin = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabelNombre.setText("Nombre");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(this::jButtonGuardarActionPerformed);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(this::jButtonEditarActionPerformed);

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(this::jButtonLimpiarActionPerformed);

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(this::jButtonConsultarActionPerformed);

        jTextFieldTelefono.addActionListener(this::jTextFieldTelefonoActionPerformed);

        jLabelApellido.setText("Apellido");

        jLabelTelefono.setText("Telefino");

        jLabelDireccion.setText("direccion");

        jTextFieldCedula.addActionListener(this::jTextFieldCedulaActionPerformed);

        jTextFieldDireccion.addActionListener(this::jTextFieldDireccionActionPerformed);

        jTextFieldApellido.addActionListener(this::jTextFieldApellidoActionPerformed);

        jLabelCedula.setText("Cedula");

        jTextFieldNombre.addActionListener(this::jTextFieldNombreActionPerformed);

        jLabelMÓDULODECLIENTES.setText("[👥 MÓDULO DE CLIENTES]");

        jLabelUsuario.setText("Usuario: Arley Londoño ");

        jLabelRol.setText(" [ Rol: Jefe ]");

        jTextFieldBuscar.addActionListener(this::jTextFieldBuscarActionPerformed);

        jLabelBuscar.setText("Buscar por Nombre o Cédula:");

        jTableclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula", "Nombre Completo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableclientes);

        jLabelClientesR.setText("Total Clientes Registrados:");

        jLabelNClientesR.setText("154");

        jButtonSalin.setText("Salir");
        jButtonSalin.addActionListener(this::jButtonSalinActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelMÓDULODECLIENTES))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCedula)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelApellido)
                                    .addComponent(jLabelTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonGuardar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSalin)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonLimpiar)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConsultar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelBuscar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelClientesR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNClientesR)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jLabelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRol)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMÓDULODECLIENTES)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabelRol))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientesR)
                            .addComponent(jLabelNClientesR)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelefono)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDireccion)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardar)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalin)))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
 * Método de apoyo encargado de sincronizar MariaDB con tu jTableclientes
 */
 public void mostrarClientes(String valor) {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new Object[][]{}, 
        new String[]{"Cédula", "Nombre Completo", "Teléfono"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Solo lectura
        }
    };
    jTableclientes.setModel(modelo);
    modelo.setRowCount(0); // Vacía filas viejas

    // 💡 CONCATENAMOS todos los campos en el WHERE para que coincida con el nombre completo que digita el usuario
    String sql = "SELECT cedula, "
               + "CONCAT(nombre, ' ', IFNULL(segundo_nombre,''), ' ', apellido, ' ', IFNULL(segundo_apellido,'')) AS nombre_completo, "
               + "telefono FROM clientes "
               + "WHERE cedula LIKE ? "
               + "OR CONCAT(nombre, ' ', IFNULL(segundo_nombre,''), ' ', apellido, ' ', IFNULL(segundo_apellido,'')) LIKE ? "
               + "OR telefono LIKE ?";

    conexion conClase = new conexion();

    try (Connection con = conClase.conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {

        // Limpiamos espacios dobles residuales que el usuario pueda escribir por error
        String buscar = "%" + valor.trim().replaceAll("\\s+", " ") + "%";
        
        ps.setString(1, buscar); // Busca por Cédula
        ps.setString(2, buscar); // Busca por Nombre Completo (Une Nombre, Snombre, Apellido, Sapellido)
        ps.setString(3, buscar); // Busca por Teléfono

        try (ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                // Reemplaza múltiples espacios en blanco por uno solo para que se vea limpio en la tabla
                String nombreFormateado = rs.getString("nombre_completo").replaceAll("\\s+", " ").trim();
                
                modelo.addRow(new Object[]{
                    rs.getString("cedula"),
                    nombreFormateado,
                    rs.getString("telefono")
                });
            }
        }
        
        // Sincroniza el contador jLabelNClientesR
        String sqlContar = "SELECT COUNT(*) AS total FROM clientes";
        try (PreparedStatement psC = con.prepareStatement(sqlContar);
             ResultSet rsC = psC.executeQuery()) {
            if (rsC.next()) {
                jLabelNClientesR.setText(String.valueOf(rsC.getInt("total")));
            }
        }

    } catch (Exception e) {
        System.err.println("Error en motor gráfico al listar clientes: " + e.getMessage());
    }
}
    
    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {                                             
    // ⬇️ AQUÍ ADENTRO PEGAS EL CÓDIGO ⬇️
    String textoBusqueda = jTextFieldBuscar.getText().trim();
    
    if (textoBusqueda.isEmpty()) {
        mostrarClientes(""); // Si está vacío, vuelve a cargar todos de la BD
    } else {
        mostrarClientes(textoBusqueda); // Si tiene texto, filtra en tiempo real
    }
}
    
    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
// 1. Validar que no dejen los campos principales vacíos (Cédula, Nombre y Apellido)
    String cedula = jTextFieldCedula.getText().trim();
    String nombresCompletos = jTextFieldNombre.getText().trim();
    String apellidosCompletos = jTextFieldApellido.getText().trim();
    
    if (cedula.isEmpty() || nombresCompletos.isEmpty() || apellidosCompletos.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "La Cédula, el Nombre y el Apellido son obligatorios", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // VARIABLES PARA LA BASE DE DATOS
    String primerNombre = "";
    String segundoNombre = ""; // Quedará vacío si solo ingresan un nombre
    String primerApellido = "";
    String segundoApellido = ""; // Quedará vacío si solo ingresan un apellido
    
    // 2. SEPARAR LOS NOMBRES (Buscando espacios en blanco)
    String[] partesNombres = nombresCompletos.split("\\s+");
    if (partesNombres.length > 0) {
        primerNombre = partesNombres[0]; 
    }
    if (partesNombres.length > 1) {
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i < partesNombres.length; i++) {
            sb.append(partesNombres[i]).append(" ");
        }
        segundoNombre = sb.toString().trim();
    }
    
    // 3. SEPARAR LOS APELLIDOS
    String[] partesApellidos = apellidosCompletos.split("\\s+");
    if (partesApellidos.length > 0) {
        primerApellido = partesApellidos[0]; 
    }
    if (partesApellidos.length > 1) {
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i < partesApellidos.length; i++) {
            sb.append(partesApellidos[i]).append(" ");
        }
        segundoApellido = sb.toString().trim();
    }

    // 4. SENTENCIA SQL ACTUALIZADA (Ahora con 7 campos)
    String sql = "INSERT INTO clientes (nombre, segundo_nombre, apellido, segundo_apellido, telefono, direccion, cedula) VALUES (?, ?, ?, ?, ?, ?, ?)";
    
    // Instanciamos tu clase de conexión nativa
    conexion conClase = new conexion(); 
    
    try (Connection con = conClase.conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        
        if (con == null) {
            return; 
        }
        
        // Mapeamos los 7 datos en el orden exacto de la consulta SQL
        ps.setString(1, primerNombre);
        ps.setString(2, segundoNombre);
        ps.setString(3, primerApellido);
        ps.setString(4, segundoApellido);
        ps.setString(5, jTextFieldTelefono.getText().trim());
        ps.setString(6, jTextFieldDireccion.getText().trim());
        ps.setString(7, cedula); // <-- Pasamos la cédula al último signo de pregunta '?'
        
        // Ejecutamos la inserción en MariaDB/MySQL
        int filasAfectadas = ps.executeUpdate();
        
        if (filasAfectadas > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Cliente registrado con éxito!");
            
            // 5. LIMPIAR TODOS LOS CAMPOS DE LA INTERFAZ
            jTextFieldCedula.setText("");
            jTextFieldNombre.setText("");
            jTextFieldApellido.setText("");
            jTextFieldTelefono.setText("");
            jTextFieldDireccion.setText("");
            
            // 🔄 6. ACTUALIZAR LA INTERFAZ EN TIEMPO REAL
            // Recarga el jTableclientes reflejando los cambios de forma automática
            mostrarClientes(""); 
        }
        
    } catch (java.sql.SQLException e) {
        // Validación inteligente por si intentan meter una cédula que ya existe (Llave duplicada)
        if (e.getErrorCode() == 1062) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ya existe un cliente registrado con la cédula " + cedula, "Registro Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de Base de Datos: " + e.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error General", javax.swing.JOptionPane.ERROR_MESSAGE);
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
    // 1. Validar que tengamos los campos obligatorios llenos
    String cedula = jTextFieldCedula.getText().trim();
    String nombresCompletos = jTextFieldNombre.getText().trim();
    String apellidosCompletos = jTextFieldApellido.getText().trim();
    
    if (cedula.isEmpty() || nombresCompletos.isEmpty() || apellidosCompletos.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un cliente de la tabla o llena los campos obligatorios para editar.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // VARIABLES PARA LA SEPARACIÓN INTELIGENTE DE NOMBRES
    String primerNombre = ""; String segundoNombre = ""; 
    String primerApellido = ""; String segundoApellido = ""; 
    
    // Separar Nombres
    String[] partesNombres = nombresCompletos.split("\\s+");
    if (partesNombres.length > 0) primerNombre = partesNombres[0];
    if (partesNombres.length > 1) {
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i < partesNombres.length; i++) sb.append(partesNombres[i]).append(" ");
        segundoNombre = sb.toString().trim();
    }
    
    // Separar Apellidos
    String[] partesApellidos = apellidosCompletos.split("\\s+");
    if (partesApellidos.length > 0) primerApellido = partesApellidos[0];
    if (partesApellidos.length > 1) {
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i < partesApellidos.length; i++) sb.append(partesApellidos[i]).append(" ");
        segundoApellido = sb.toString().trim();
    }

    // 2. SENTENCIA SQL DE ACTUALIZACIÓN
    String sql = "UPDATE clientes SET nombre=?, segundo_nombre=?, apellido=?, segundo_apellido=?, telefono=?, direccion=? WHERE cedula=?";
    conexion conClase = new conexion();

    try (Connection con = conClase.conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        
        if (con == null) return;

        // Mapeamos los parámetros ordenados de las columnas hacia el WHERE
        ps.setString(1, primerNombre);
        ps.setString(2, segundoNombre);
        ps.setString(3, primerApellido);
        ps.setString(4, segundoApellido);
        ps.setString(5, jTextFieldTelefono.getText().trim());
        ps.setString(6, jTextFieldDireccion.getText().trim());
        ps.setString(7, cedula); // Identificador único para el WHERE

        int filasAfectadas = ps.executeUpdate();
        
        if (filasAfectadas > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Datos del cliente actualizados con éxito!");
            mostrarClientes(""); // Refresca tu jTableclientes automáticamente
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún cliente con esa cédula para modificar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al editar registro: " + e.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
    }    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
    // 🧹 Deja todas las casillas de texto completamente en blanco
    jTextFieldCedula.setText("");
    jTextFieldNombre.setText("");
    jTextFieldApellido.setText("");
    jTextFieldTelefono.setText("");
    jTextFieldDireccion.setText("");
    
    // 🔍 Opcional: Si quieres que el buscador también se limpie y la tabla vuelva a mostrar todos:
    if (jTextFieldBuscar != null) {
        jTextFieldBuscar.setText("");
    }
    mostrarClientes(""); 
    
    // Pone el foco del teclado en la cédula para que sea cómodo volver a escribir
    jTextFieldCedula.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
    mostrarClientes(jTextFieldBuscar.getText().trim());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonSalinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalinActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalin;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelClientesR;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelMÓDULODECLIENTES;
    private javax.swing.JLabel jLabelNClientesR;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableclientes;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    
}
