/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author darie
 */
public class FrmProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProveedores
     */
    public FrmProveedores() {
        initComponents();
        jTextFieldIDproveedor.setEnabled(false); // El ID es auto_increment, se bloquea.
        mostrarProveedores("");                 // Carga inicial de la tabla
        configurarBuscadorYTabla();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelGESTIÓNDEPROVEEDORESDISTRIBUIDORASDECARNE = new javax.swing.JLabel();
        jLabelIDProveedor = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelNombres = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelDirección = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNECT = new javax.swing.JTable();
        jLabeltOTAL = new javax.swing.JLabel();
        jLabeltOTAL2 = new javax.swing.JLabel();
        jTextFieldIDproveedor = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldNombres = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelRazónSocial = new javax.swing.JLabel();
        jTextFieldRazonsocial = new javax.swing.JTextField();

        jLabelGESTIÓNDEPROVEEDORESDISTRIBUIDORASDECARNE.setText("🚚 GESTIÓN DE PROVEEDORES (DISTRIBUIDORAS DE CARNE)");

        jLabelIDProveedor.setText("ID Proveedor:");

        jLabelCedula.setText("Cédula:");

        jLabelNombres.setText("Nombres");

        jLabelApellidos.setText("Apellidos");

        jLabelTelefono.setText("Teléfono:");

        jLabelDirección.setText("Dirección:");

        jLabelCorreo.setText("Correo:");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(this::jButtonGuardarActionPerformed);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(this::jButtonEditarActionPerformed);

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(this::jButtonLimpiarActionPerformed);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(this::jButtonSalirActionPerformed);

        jLabelBuscar.setText("Buscar (Empresa/NIT/Cont.):");

        jTextFieldBuscar.addActionListener(this::jTextFieldBuscarActionPerformed);

        jTableNECT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIT", "Empresa", "Contacto Principal", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNECT);

        jLabeltOTAL.setText("Total Proveedores:");

        jLabeltOTAL2.setText("1");

        jTextFieldIDproveedor.addActionListener(this::jTextFieldIDproveedorActionPerformed);

        jTextFieldCedula.addActionListener(this::jTextFieldCedulaActionPerformed);

        jTextFieldNombres.addActionListener(this::jTextFieldNombresActionPerformed);

        jTextFieldApellidos.addActionListener(this::jTextFieldApellidosActionPerformed);

        jTextFieldTelefono.addActionListener(this::jTextFieldTelefonoActionPerformed);

        jTextFieldDireccion.addActionListener(this::jTextFieldDireccionActionPerformed);

        jTextFieldCorreo.addActionListener(this::jTextFieldCorreoActionPerformed);

        jLabelRazónSocial.setText("Razón Social:");

        jTextFieldRazonsocial.addActionListener(this::jTextFieldRazonsocialActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGESTIÓNDEPROVEEDORESDISTRIBUIDORASDECARNE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelRazónSocial)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldRazonsocial))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelCorreo)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldCorreo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelDirección)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldDireccion))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelTelefono)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldTelefono))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelApellidos)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldApellidos))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelNombres)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNombres))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelCedula)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldCedula))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelIDProveedor)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldIDproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSalir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditar)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabeltOTAL)
                        .addGap(18, 18, 18)
                        .addComponent(jLabeltOTAL2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGESTIÓNDEPROVEEDORESDISTRIBUIDORASDECARNE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDProveedor)
                    .addComponent(jLabelBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIDproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRazónSocial)
                            .addComponent(jTextFieldRazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCedula)
                            .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombres)
                            .addComponent(jTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidos)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelefono)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDirección)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCorreo)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jLabeltOTAL)
                    .addComponent(jLabeltOTAL2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void mostrarProveedores(String valor) {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"ID", "NIT", "Empresa / Distribuidora", "Contacto Principal", "Teléfono"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Solo lectura
            }
        };
        jTableNECT.setModel(modelo);
        modelo.setRowCount(0);

        // Busca coincidencias por Razón Social, Nombre del asesor o por el NIT
        String sql = "SELECT id_proveedor, nit, nombre_empresa, nombre_contacto, apellido_contacto, telefono "
                   + "FROM proveedores "
                   + "WHERE nombre_empresa LIKE ? OR nombre_contacto LIKE ? OR nit LIKE ? "
                   + "ORDER BY id_proveedor DESC";
        
        conexion conClase = new conexion();

        try (Connection con = conClase.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            String query = "%" + valor.trim() + "%";
            ps.setString(1, query);
            ps.setString(2, query);
            ps.setString(3, query);

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    String contactoCompleto = rs.getString("nombre_contacto") + " " + rs.getString("apellido_contacto");

                    modelo.addRow(new Object[]{
                        rs.getInt("id_proveedor"),
                        rs.getString("nit") != null ? rs.getString("nit") : "N/A",
                        rs.getString("nombre_empresa"),
                        contactoCompleto.trim(),
                        rs.getString("telefono") != null ? rs.getString("telefono") : "N/A"
                    });
                }
            }
            
            // Actualiza dinámicamente el contador de proveedores (jLabeltOTAL2)
            String sqlContar = "SELECT COUNT(*) AS total FROM proveedores";
            try (PreparedStatement psC = con.prepareStatement(sqlContar);
                 ResultSet rsC = psC.executeQuery()) {
                if (rsC.next()) {
                    jLabeltOTAL2.setText(String.valueOf(rsC.getInt("total")));
                }
            }

        } catch (Exception e) {
            System.err.println("Error al listar proveedores: " + e.getMessage());
        }
    }

    /**
     * Controla las acciones reactivas de la tabla y la caja de texto buscar
     */
    private void configurarBuscadorYTabla() {
        // Ejecuta el filtro dinámico cada vez que se suelta una tecla en el buscador
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mostrarProveedores(jTextFieldBuscar.getText().trim());
            }
        });

        // Evento mouse para transferir los datos de la fila de la JTable de vuelta a los JTextField
        jTableNECT.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = jTableNECT.getSelectedRow();
                if (fila >= 0) {
                    // Obtenemos el ID desde la primera columna invisible de la JTable
                    String id = jTableNECT.getValueAt(fila, 0).toString();
                    
                    String sql = "SELECT * FROM proveedores WHERE id_proveedor = ?";
                    conexion conClase = new conexion();
                    try (Connection con = conClase.conectar();
                         PreparedStatement ps = con.prepareStatement(sql)) {
                        ps.setInt(1, Integer.parseInt(id));
                        try (ResultSet rs = ps.executeQuery()) {
                            if (rs.next()) {
                                jTextFieldIDproveedor.setText(rs.getString("id_proveedor"));
                                jTextFieldCedula.setText(rs.getString("nit"));
                                jTextFieldRazonsocial.setText(rs.getString("nombre_empresa"));
                                
                                // Reconstruye los nombres (primer y segundo) en un solo campo de texto
                                String nombresJuntos = rs.getString("nombre_contacto") + 
                                        (rs.getString("segundo_nombre_contacto") != null ? " " + rs.getString("segundo_nombre_contacto") : "");
                                jTextFieldNombres.setText(nombresJuntos.trim());
                                
                                // Reconstruye los apellidos (primer y segundo) en un solo campo de texto
                                String apellidosJuntos = rs.getString("apellido_contacto") + 
                                        (rs.getString("segundo_apellido_contacto") != null ? " " + rs.getString("segundo_apellido_contacto") : "");
                                jTextFieldApellidos.setText(apellidosJuntos.trim());
                                
                                jTextFieldTelefono.setText(rs.getString("telefono"));
                                jTextFieldDireccion.setText(rs.getString("direccion"));
                                jTextFieldCorreo.setText(rs.getString("correo"));
                            }
                        }
                    } catch (Exception ex) {
                        System.err.println("Error al recuperar proveedor: " + ex.getMessage());
                    }
                }
            }
        });
    }
    
   
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        String nit = jTextFieldCedula.getText().trim(); // Guardamos el NIT/Cédula en su campo respectivo
        String empresa = jTextFieldRazonsocial.getText().trim();
        String nombresFull = jTextFieldNombres.getText().trim();
        String apellidosFull = jTextFieldApellidos.getText().trim();
        
        // Validación en caliente de campos indispensables
        if (nit.isEmpty() || empresa.isEmpty() || nombresFull.isEmpty() || apellidosFull.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "NIT, Razón Social, Nombres y Apellidos son obligatorios.", "Campos Vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Divide inteligentemente los nombres por espacios para rellenar las columnas de MariaDB
        String[] partesNombres = nombresFull.split("\\s+");
        String pNombre = partesNombres[0];
        String sNombre = (partesNombres.length > 1) ? nombresFull.substring(pNombre.length()).trim() : null;

        // Divide inteligentemente los apellidos por espacios para rellenar las columnas de MariaDB
        String[] partesApellidos = apellidosFull.split("\\s+");
        String pApellido = partesApellidos[0];
        String sApellido = (partesApellidos.length > 1) ? apellidosFull.substring(pApellido.length()).trim() : null;

        String sql = "INSERT INTO proveedores (nombre_empresa, nombre_contacto, segundo_nombre_contacto, apellido_contacto, segundo_apellido_contacto, telefono, direccion, correo, nit) VALUES (?,?,?,?,?,?,?,?,?)";
        conexion conClase = new conexion();

        try (Connection con = conClase.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, empresa);
            ps.setString(2, pNombre);
            ps.setString(3, sNombre);
            ps.setString(4, pApellido);
            ps.setString(5, sApellido);
            ps.setString(6, jTextFieldTelefono.getText().trim().isEmpty() ? null : jTextFieldTelefono.getText().trim());
            ps.setString(7, jTextFieldDireccion.getText().trim().isEmpty() ? null : jTextFieldDireccion.getText().trim());
            ps.setString(8, jTextFieldCorreo.getText().trim().isEmpty() ? null : jTextFieldCorreo.getText().trim());
            ps.setString(9, nit);

            if (ps.executeUpdate() > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Distribuidora registrada exitosamente!");
                jButtonLimpiarActionPerformed(null);
            }
        } catch (java.sql.SQLException e) {
            if (e.getErrorCode() == 1062) { // Captura de la restricción UNIQUE de MariaDB
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El NIT/Cédula '" + nit + "' ya se encuentra registrado.", "Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error General: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        String idStr = jTextFieldIDproveedor.getText().trim();
        String nit = jTextFieldCedula.getText().trim();
        String empresa = jTextFieldRazonsocial.getText().trim();
        String nombresFull = jTextFieldNombres.getText().trim();
        String apellidosFull = jTextFieldApellidos.getText().trim();

        if (idStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un proveedor de la tabla para modificarlo.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (nit.isEmpty() || empresa.isEmpty() || nombresFull.isEmpty() || apellidosFull.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No puede dejar en blanco los campos obligatorios.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Divide los textos para la actualización individual por columnas
        String[] partesNombres = nombresFull.split("\\s+");
        String pNombre = partesNombres[0];
        String sNombre = (partesNombres.length > 1) ? nombresFull.substring(pNombre.length()).trim() : null;

        String[] partesApellidos = apellidosFull.split("\\s+");
        String pApellido = partesApellidos[0];
        String sApellido = (partesApellidos.length > 1) ? apellidosFull.substring(pApellido.length()).trim() : null;

        String sql = "UPDATE proveedores SET nombre_empresa=?, nombre_contacto=?, segundo_nombre_contacto=?, apellido_contacto=?, segundo_apellido_contacto=?, telefono=?, direccion=?, correo=?, nit=? WHERE id_proveedor=?";
        conexion conClase = new conexion();

        try (Connection con = conClase.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, empresa);
            ps.setString(2, pNombre);
            ps.setString(3, sNombre);
            ps.setString(4, pApellido);
            ps.setString(5, sApellido);
            ps.setString(6, jTextFieldTelefono.getText().trim().isEmpty() ? null : jTextFieldTelefono.getText().trim());
            ps.setString(7, jTextFieldDireccion.getText().trim().isEmpty() ? null : jTextFieldDireccion.getText().trim());
            ps.setString(8, jTextFieldCorreo.getText().trim().isEmpty() ? null : jTextFieldCorreo.getText().trim());
            ps.setString(9, nit);
            ps.setInt(10, Integer.parseInt(idStr));

            if (ps.executeUpdate() > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Datos de la distribuidora actualizados correctamente.");
                jButtonLimpiarActionPerformed(null);
            }
        } catch (java.sql.SQLException e) {
            if (e.getErrorCode() == 1062) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El NIT/Cédula '" + nit + "' ya está en uso por otro proveedor.", "Conflicto", javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error General", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldIDproveedor.setText("");
        jTextFieldCedula.setText("");
        jTextFieldRazonsocial.setText("");
        jTextFieldNombres.setText("");
        jTextFieldApellidos.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldCorreo.setText("");
        jTextFieldBuscar.setText("");
        
        mostrarProveedores("");          // Restablece la tabla completa sin filtros
        jTextFieldCedula.requestFocus();  // Devuelve el cursor al primer campo útil
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jTextFieldIDproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDproveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDproveedorActionPerformed

    private void jTextFieldRazonsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRazonsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRazonsocialActionPerformed

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed

    private void jTextFieldNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombresActionPerformed

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDirección;
    private javax.swing.JLabel jLabelGESTIÓNDEPROVEEDORESDISTRIBUIDORASDECARNE;
    private javax.swing.JLabel jLabelIDProveedor;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelRazónSocial;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabeltOTAL;
    private javax.swing.JLabel jLabeltOTAL2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNECT;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldIDproveedor;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextFieldRazonsocial;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
