/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darie
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

   private DefaultTableModel modeloTabla;
    
    /**
     * Creates new form FmrUsuarios
     */
    public FrmUsuarios() {
       
       initComponents();
       configurarTabla();
        configurarCombosIniciales();
        configurarEventoTabla();
        configurarEventoBuscar();
        listarUsuarios();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jLabelEstadoC = new javax.swing.JLabel();
        jLabelGESTIÓN = new javax.swing.JLabel();
        jLabelIdCedula = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNombreU = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        jComboBoxRolsistema = new javax.swing.JComboBox<>();
        jComboBoxEstadoC = new javax.swing.JComboBox<>();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNUR = new javax.swing.JTable();
        jLabelTotalU = new javax.swing.JLabel();
        jLabelNusuario = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelCargodelaEmpresa = new javax.swing.JLabel();
        jComboBoxCargodelaempresa = new javax.swing.JComboBox<>();

        jLabelContraseña.setText("Contraseña *:");

        jLabelRol.setText("Rol de Sistema *:");

        jLabelEstadoC.setText("Estado Cuenta *:");

        jLabelGESTIÓN.setText("👥 GESTIÓN DE USUARIOS Y CONTROL DE ACCESOS (SISTEMA CARNICERÍA)");

        jLabelIdCedula.setText("Cedula");

        jLabelNombre.setText("Nombre Completo *:");

        jLabelNombreU.setText("Nombre Usuario *");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(this::jButtonGuardarActionPerformed);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(this::jButtonEditarActionPerformed);

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(this::jButtonLimpiarActionPerformed);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(this::jButtonSalirActionPerformed);

        jTextFieldCedula.addActionListener(this::jTextFieldCedulaActionPerformed);

        jTextFieldNombre.addActionListener(this::jTextFieldNombreActionPerformed);

        jTextFieldUsuario.addActionListener(this::jTextFieldUsuarioActionPerformed);

        jPasswordFieldContrasena.addActionListener(this::jPasswordFieldContrasenaActionPerformed);

        jComboBoxRolsistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRolsistema.addActionListener(this::jComboBoxRolsistemaActionPerformed);

        jComboBoxEstadoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEstadoC.addActionListener(this::jComboBoxEstadoCActionPerformed);

        jLabelBuscar.setText("Buscar (Nombre/Usuario):");

        jTextFieldBuscar.addActionListener(this::jTextFieldBuscarActionPerformed);

        jTableNUR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Telefono", "Cargo", "Rol", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNUR);

        jLabelTotalU.setText("Total Usuarios:");

        jLabelTelefono.setText("Teléfono:");

        jTextFieldTelefono.addActionListener(this::jTextFieldTelefonoActionPerformed);

        jLabelCargodelaEmpresa.setText("Cargo de la Empresa:");

        jComboBoxCargodelaempresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCargodelaempresa.addActionListener(this::jComboBoxCargodelaempresaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelGESTIÓN)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelIdCedula)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCedula))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCargodelaEmpresa)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxCargodelaempresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jButtonGuardar)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonSalir)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonEditar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonLimpiar))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelNombreU)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldUsuario))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelContraseña)
                            .addGap(18, 18, 18)
                            .addComponent(jPasswordFieldContrasena))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelRol)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxRolsistema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelEstadoC)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxEstadoC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTotalU)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBuscar)
                        .addGap(34, 34, 34)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGESTIÓN)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdCedula))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalU)
                            .addComponent(jLabelNusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelefono)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCargodelaEmpresa)
                            .addComponent(jComboBoxCargodelaempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreU)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelContraseña)
                            .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRol)
                            .addComponent(jComboBoxRolsistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEstadoC)
                            .addComponent(jComboBoxEstadoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardar)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonLimpiar))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Cédula", "Nombre Completo", "Teléfono", "Cargo de la Empresa", "Rol de Sistema", "Estado de Cuenta"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableNUR.setModel(modeloTabla);
    }
    
    private void configurarCombosIniciales() {
        jComboBoxRolsistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe", "Empleado" }));
        jComboBoxEstadoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jComboBoxCargodelaempresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe", "Administrador", "Cajero", "Carnicero Principal", "Auxiliar de Vitrina" }));
    }

    public void listarUsuarios() {
        ejecutarConsultaBusqueda("");
    }

    private void ejecutarConsultaBusqueda(String valorBuscar) {
    modeloTabla.setRowCount(0);
    
    // Corregido: r.nombre_rol es el nombre real en tu tabla 'roles'
    String sql = "SELECT u.cedula, u.nombre, u.telefono, u.cargo, u.usuario, u.estado, r.nombre_rol AS rol_nombre "
               + "FROM usuarios u "
               + "INNER JOIN roles r ON u.id_rol = r.id_rol "
               + "WHERE u.nombre LIKE ? OR u.usuario LIKE ? OR u.cedula LIKE ? "
               + "ORDER BY u.nombre ASC";
               
    int totalUsuarios = 0;

    conexion cc = new conexion();
    try (Connection con = cc.conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, "%" + valorBuscar + "%");
        ps.setString(2, "%" + valorBuscar + "%");
        ps.setString(3, "%" + valorBuscar + "%");
        
        try (ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getString("cedula");
                fila[1] = rs.getString("nombre");      // Nombre completo de la persona
                fila[2] = rs.getString("telefono");
                fila[3] = rs.getString("cargo");
                
                // Ahora sí traerá de forma estricta "Jefe" o "Empleado" (o como los tengas mapeados)
                String rolObtenido = rs.getString("rol_nombre"); 
                fila[4] = (rolObtenido != null && !rolObtenido.isEmpty()) ? rolObtenido : "Empleado";
                
                fila[5] = rs.getString("estado");

                modeloTabla.addRow(fila);
                totalUsuarios++;
            }
        }
        jLabelNusuario.setText(String.valueOf(totalUsuarios));

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al procesar usuarios: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void configurarEventoTabla() {
        jTableNUR.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int filaSeleccionada = jTableNUR.getSelectedRow();
                if (filaSeleccionada >= 0) {
                    
                    int filaModelo = jTableNUR.convertRowIndexToModel(filaSeleccionada);

                    String cedula   = modeloTabla.getValueAt(filaModelo, 0) != null ? modeloTabla.getValueAt(filaModelo, 0).toString().trim() : "";
                    String nombre   = modeloTabla.getValueAt(filaModelo, 1) != null ? modeloTabla.getValueAt(filaModelo, 1).toString().trim() : "";
                    String telefono = modeloTabla.getValueAt(filaModelo, 2) != null ? modeloTabla.getValueAt(filaModelo, 2).toString().trim() : "";
                    String cargo    = modeloTabla.getValueAt(filaModelo, 3) != null ? modeloTabla.getValueAt(filaModelo, 3).toString().trim() : "";
                    String rol      = modeloTabla.getValueAt(filaModelo, 4) != null ? modeloTabla.getValueAt(filaModelo, 4).toString().trim() : "";
                    String estado   = modeloTabla.getValueAt(filaModelo, 5) != null ? modeloTabla.getValueAt(filaModelo, 5).toString().trim() : "";

                    jTextFieldCedula.setText(cedula);
                    jTextFieldNombre.setText(nombre);
                    jTextFieldTelefono.setText(telefono);
                    
                    jComboBoxCargodelaempresa.setSelectedItem(cargo.isEmpty() ? "Jefe" : cargo);
                    jComboBoxEstadoC.setSelectedItem(estado.isEmpty() ? "Activo" : estado);

                    jComboBoxRolsistema.setSelectedIndex(-1);
                    String rolUpper = rol.toUpperCase();
                    if (rolUpper.contains("JEFE")) {
                        jComboBoxRolsistema.setSelectedItem("Jefe");
                    } else {
                        jComboBoxRolsistema.setSelectedItem("Empleado");
                    }

                    if (!cedula.isEmpty()) {
                        recuperarCredencialesUsuario(cedula);
                    }
                }
            }
        });
    }
    
    private void recuperarCredencialesUsuario(String cedula) {
        String sql = "SELECT usuario, clave FROM usuarios WHERE cedula = ?";
        conexion cc = new conexion();
        try (Connection con = cc.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            ps.setString(1, cedula);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    jTextFieldUsuario.setText(rs.getString("usuario"));
                    jPasswordFieldContrasena.setText(rs.getString("clave"));
                }
            }
        } catch (SQLException e) {
            System.out.println("Error al recuperar credenciales: " + e.getMessage());
        }
    }
    
    private void configurarEventoBuscar() {
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ejecutarConsultaBusqueda(jTextFieldBuscar.getText().trim());
            }
        });
    }

    private void limpiarFormulario() {
        jTextFieldCedula.setText("");
        jTextFieldNombre.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldContrasena.setText("");
        jComboBoxCargodelaempresa.setSelectedIndex(0);
        jComboBoxRolsistema.setSelectedIndex(0);
        jComboBoxEstadoC.setSelectedIndex(0);
        jTextFieldCedula.requestFocus();
    }
    
    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jPasswordFieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContrasenaActionPerformed

    private void jComboBoxRolsistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRolsistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRolsistemaActionPerformed

    private void jComboBoxEstadoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoCActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

   String cedula = jTextFieldCedula.getText().trim();
        String nombre = jTextFieldNombre.getText().trim();
        String telefono = jTextFieldTelefono.getText().trim();
        String cargo = jComboBoxCargodelaempresa.getSelectedItem().toString();
        String usuario = jTextFieldUsuario.getText().trim();
        String clave = new String(jPasswordFieldContrasena.getPassword()).trim();
        String rolSeleccionado = jComboBoxRolsistema.getSelectedItem().toString();
        String estado = jComboBoxEstadoC.getSelectedItem().toString();

        // Validaciones básicas de campos obligatorios marcados con *
        if (cedula.isEmpty() || nombre.isEmpty() || usuario.isEmpty() || clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios (*)", "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idRol = obtenerIdRolPorNombre(rolSeleccionado);

        String sql = "INSERT INTO usuarios (cedula, nombre, telefono, cargo, usuario, clave, id_rol, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
        conexion cc = new conexion();
        try (Connection con = cc.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            ps.setString(1, cedula);
            ps.setString(2, nombre);
            ps.setString(3, telefono);
            ps.setString(4, cargo);
            ps.setString(5, usuario);
            ps.setString(6, clave);
            ps.setInt(7, idRol);
            ps.setString(8, estado);

            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el usuario: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        } 

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        String cedula = jTextFieldCedula.getText().trim();
        String nombre = jTextFieldNombre.getText().trim();
        String telefono = jTextFieldTelefono.getText().trim();
        String cargo = jComboBoxCargodelaempresa.getSelectedItem().toString();
        String usuario = jTextFieldUsuario.getText().trim();
        String clave = new String(jPasswordFieldContrasena.getPassword()).trim();
        String rolSeleccionado = jComboBoxRolsistema.getSelectedItem().toString();
        String estado = jComboBoxEstadoC.getSelectedItem().toString();

        if (cedula.isEmpty() || nombre.isEmpty() || usuario.isEmpty() || clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla y complete los campos obligatorios (*)", "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idRol = obtenerIdRolPorNombre(rolSeleccionado);

        String sql = "UPDATE usuarios SET nombre = ?, telefono = ?, cargo = ?, usuario = ?, clave = ?, id_rol = ?, estado = ? WHERE cedula = ?";
        
        conexion cc = new conexion();
        try (Connection con = cc.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            ps.setString(1, nombre);
            ps.setString(2, telefono);
            ps.setString(3, cargo);
            ps.setString(4, usuario);
            ps.setString(5, clave);
            ps.setInt(6, idRol);
            ps.setString(7, estado);
            ps.setString(8, cedula);

            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el usuario con la cédula especificada.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el usuario: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

 limpiarFormulario();     
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
   
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jComboBoxCargodelaempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCargodelaempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCargodelaempresaActionPerformed

private int obtenerIdRolPorNombre(String nombreRol) {
        if (nombreRol != null && nombreRol.equalsIgnoreCase("Jefe")) {
            return 1; 
        }
        return 2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxCargodelaempresa;
    private javax.swing.JComboBox<String> jComboBoxEstadoC;
    private javax.swing.JComboBox<String> jComboBoxRolsistema;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCargodelaEmpresa;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelEstadoC;
    private javax.swing.JLabel jLabelGESTIÓN;
    private javax.swing.JLabel jLabelIdCedula;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreU;
    private javax.swing.JLabel jLabelNusuario;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTotalU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNUR;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    
}
