/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
    
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author darie
 */
public class Reportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonReporteC = new javax.swing.JButton();

        jButton1.setText("Reportes de Productos");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButtonReporteC.setText("Reportes de Clientes");
        jButtonReporteC.addActionListener(this::jButtonReporteCActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButtonReporteC)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(52, 52, 52)
                .addComponent(jButtonReporteC)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Connection con = null;
    try {
        con = new conexion().conectar();
        
        // Carga automática y segura sin importar en qué computador se ejecute
        java.io.InputStream rutaReporte = getClass().getResourceAsStream("/Reportes/ReporteProductos.jrxml");
        
        if (rutaReporte == null) {
            JOptionPane.showMessageDialog(this, 
                "No se encontró 'ReporteProductos.jrxml' en la carpeta src/Reportes/", 
                "Archivo No Encontrado", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JasperReport jasperReport = JasperCompileManager.compileReport(rutaReporte);
        Map<String, Object> parametros = new HashMap<>();
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, con);
        
        JasperViewer visor = new JasperViewer(jasperPrint, false);
        visor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        visor.setTitle("Reporte de Productos en Existencia");
        visor.setVisible(true);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al generar el reporte: " + e.getMessage(), 
            "Error JasperReports", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        try {
            if (con != null && !con.isClosed()) {
                con.close();
            }
        } catch (Exception ex) {
            System.err.println("Error al cerrar conexión: " + ex.getMessage());
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonReporteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteCActionPerformed
       
        Connection con = null;
    try {
        con = new conexion().conectar();
        
        // Carga automática y segura sin importar en qué computador se ejecute
        java.io.InputStream rutaReporte = getClass().getResourceAsStream("/Reportes/ReporteClientes.jrxml");
        
        if (rutaReporte == null) {
            JOptionPane.showMessageDialog(this, 
                "No se encontró 'ReporteClientes.jrxml' en la carpeta src/Reportes/", 
                "Archivo No Encontrado", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JasperReport jasperReport = JasperCompileManager.compileReport(rutaReporte);
        Map<String, Object> parametros = new HashMap<>();
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, con);
        
        JasperViewer visor = new JasperViewer(jasperPrint, false);
        visor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        visor.setTitle("Reporte de Productos en Existencia");
        visor.setVisible(true);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al generar el reporte: " + e.getMessage(), 
            "Error JasperReports", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        try {
            if (con != null && !con.isClosed()) {
                con.close();
            }
        } catch (Exception ex) {
            System.err.println("Error al cerrar conexión: " + ex.getMessage());
        }
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonReporteCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonReporteC;
    // End of variables declaration//GEN-END:variables
}
