/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darie
 */
public class VistaGeneralPuntodeVentayPesajes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGeneralPuntodeVentayPesajes.class.getName());

    
        // Variables lógicas añadidas para el control de la caja de la carnicería
    private DefaultTableModel modeloFactura;
    private double totalFactura = 0.0;
    private double stockActualProducto = 0.0;
    private String codigoProductoActual = "";
    
    /**
     * Creates new form a
     */
    public VistaGeneralPuntodeVentayPesajes() {
        initComponents();
        configurarLogicaVentas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelTextomenu = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelBÁSCULA = new javax.swing.JLabel();
        jLabelPRODUCTOSELECCIONADO = new javax.swing.JLabel();
        jLabelPRECIOPORKILO = new javax.swing.JLabel();
        jTextFieldPRECIOPORKILO = new javax.swing.JTextField();
        jLabelPESOADESPACHAR = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabelVALORTOTALDELCORTE = new javax.swing.JLabel();
        jLabelDETALLEDELAFACTURAACTUAL = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFactura = new javax.swing.JTable();
        jLabelPÁGINADECIERREYMÉTODOSDEPAGO = new javax.swing.JLabel();
        jComboBoxClienteCedula = new javax.swing.JComboBox<>();
        jLabelClienteCedula = new javax.swing.JLabel();
        jLabelATAJOSTECLADO = new javax.swing.JLabel();
        jButtonEfectivo = new javax.swing.JButton();
        jLabelF1NuevaVenta = new javax.swing.JLabel();
        jLabelF2BuscarProducto = new javax.swing.JLabel();
        jLabelEmpresa = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCategorias = new javax.swing.JButton();
        jButtonProveedores = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonCompras = new javax.swing.JButton();
        jLabelTextoCondiguracion = new javax.swing.JLabel();
        jButtonReportes = new javax.swing.JButton();
        jButtonCerrarSesión = new javax.swing.JButton();
        jLabelMétodo = new javax.swing.JLabel();
        jButtonTarjeta = new javax.swing.JButton();
        jLabelF3IngresarMerma = new javax.swing.JLabel();
        jButtonNequi = new javax.swing.JButton();
        jLabelF4CerrarCajaTurno = new javax.swing.JLabel();
        jLabelTOTALAPAGAR = new javax.swing.JLabel();
        jLabelNdC = new javax.swing.JLabel();
        jLabelNombredeC = new javax.swing.JLabel();
        jComboBoxPRODUCTOSELECCIONADO = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTextomenu.setText("MENÚ DE MÓDULOS");

        jLabelTotal.setText("$ 77.000");

        jLabelBÁSCULA.setText("BÁSCULA CALCULADORA");

        jLabelPRODUCTOSELECCIONADO.setText("PRODUCTO SELECCIONADO:");

        jLabelPRECIOPORKILO.setText("PRECIO POR KILO:");

        jTextFieldPRECIOPORKILO.addActionListener(this::jTextFieldPRECIOPORKILOActionPerformed);

        jLabelPESOADESPACHAR.setText("PESO A DESPACHAR");

        jTextFieldPeso.addActionListener(this::jTextFieldPesoActionPerformed);

        jLabelVALORTOTALDELCORTE.setText("VALOR TOTAL DEL CORTE:");

        jLabelDETALLEDELAFACTURAACTUAL.setText("DETALLE DE LA FACTURA ACTUAL");

        jLabelValor.setText("$ 50.000");

        jTableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cód. Barras", "Corte de Carne", "Precio / KG", "Peso (KG)", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTableFactura);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabelPÁGINADECIERREYMÉTODOSDEPAGO.setText("PÁGINA DE CIERRE Y MÉTODOS DE PAGO");

        jComboBoxClienteCedula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxClienteCedula.addActionListener(this::jComboBoxClienteCedulaActionPerformed);

        jLabelClienteCedula.setText("Cliente:");

        jLabelATAJOSTECLADO.setText("ATAJOS TECLADO:");

        jButtonEfectivo.setText("Efectivo");
        jButtonEfectivo.addActionListener(this::jButtonEfectivoActionPerformed);

        jLabelF1NuevaVenta.setText("F1: Nueva Venta");

        jLabelF2BuscarProducto.setText("F2: Buscar Producto");

        jLabelEmpresa.setText("[] SISTEMA CARNICERÍA \"EL CORTE\"");

        jToolBar1.setBackground(new java.awt.Color(153, 255, 153));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonCategorias.setText("Categorias");
        jButtonCategorias.setFocusable(false);
        jButtonCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCategorias.addActionListener(this::jButtonCategoriasActionPerformed);
        jToolBar1.add(jButtonCategorias);

        jButtonProveedores.setText("Proveedores");
        jButtonProveedores.setFocusable(false);
        jButtonProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProveedores.addActionListener(this::jButtonProveedoresActionPerformed);
        jToolBar1.add(jButtonProveedores);

        jButtonClientes.setText("Clientes");
        jButtonClientes.setFocusable(false);
        jButtonClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClientes.addActionListener(this::jButtonClientesActionPerformed);
        jToolBar1.add(jButtonClientes);

        jButtonProductos.setText("Productos");
        jButtonProductos.setFocusable(false);
        jButtonProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProductos.addActionListener(this::jButtonProductosActionPerformed);
        jToolBar1.add(jButtonProductos);

        jButtonUsuarios.setText("Usuarios");
        jButtonUsuarios.setFocusable(false);
        jButtonUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUsuarios.addActionListener(this::jButtonUsuariosActionPerformed);
        jToolBar1.add(jButtonUsuarios);

        jButtonCompras.setText("Compras");
        jButtonCompras.setFocusable(false);
        jButtonCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCompras.addActionListener(this::jButtonComprasActionPerformed);
        jToolBar1.add(jButtonCompras);

        jLabelTextoCondiguracion.setText("CONFIGURACIÓN");
        jToolBar1.add(jLabelTextoCondiguracion);

        jButtonReportes.setText("Reportes");
        jButtonReportes.setFocusable(false);
        jButtonReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReportes.addActionListener(this::jButtonReportesActionPerformed);
        jToolBar1.add(jButtonReportes);

        jButtonCerrarSesión.setText("Cerrar Sesión");
        jButtonCerrarSesión.setFocusable(false);
        jButtonCerrarSesión.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCerrarSesión.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCerrarSesión.addActionListener(this::jButtonCerrarSesiónActionPerformed);
        jToolBar1.add(jButtonCerrarSesión);

        jLabelMétodo.setText("Método:");

        jButtonTarjeta.setText("Tarjeta");
        jButtonTarjeta.addActionListener(this::jButtonTarjetaActionPerformed);

        jLabelF3IngresarMerma.setText("F3: Ingresar Merma");

        jButtonNequi.setText("Nequi");
        jButtonNequi.addActionListener(this::jButtonNequiActionPerformed);

        jLabelF4CerrarCajaTurno.setText("F4: Cerrar Caja / Turno");

        jLabelTOTALAPAGAR.setText("TOTAL A PAGAR:");

        jLabelNdC.setText("Nombre de Cliente");

        jLabelNombredeC.setText("N");

        jComboBoxPRODUCTOSELECCIONADO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabelTextomenu)))
                            .addComponent(jLabelATAJOSTECLADO))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelF1NuevaVenta)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelF2BuscarProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelF3IngresarMerma))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelClienteCedula)
                                            .addComponent(jLabelMétodo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboBoxClienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelNdC))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonEfectivo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonTarjeta)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonNequi)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelNombredeC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelTOTALAPAGAR)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelF4CerrarCajaTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))))
                            .addComponent(jLabelPÁGINADECIERREYMÉTODOSDEPAGO)
                            .addComponent(jLabelBÁSCULA)
                            .addComponent(jLabelDETALLEDELAFACTURAACTUAL)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPRECIOPORKILO)
                                            .addComponent(jLabelPRODUCTOSELECCIONADO))
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelPESOADESPACHAR))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelVALORTOTALDELCORTE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxPRODUCTOSELECCIONADO, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPRECIOPORKILO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelEmpresa))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTextomenu)
                            .addComponent(jLabelBÁSCULA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPRODUCTOSELECCIONADO)
                                    .addComponent(jComboBoxPRODUCTOSELECCIONADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPRECIOPORKILO)
                                    .addComponent(jTextFieldPRECIOPORKILO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPESOADESPACHAR)
                                    .addComponent(jLabelVALORTOTALDELCORTE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelValor))
                                .addGap(47, 47, 47)
                                .addComponent(jLabelDETALLEDELAFACTURAACTUAL)
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPÁGINADECIERREYMÉTODOSDEPAGO)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClienteCedula)
                            .addComponent(jComboBoxClienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTOTALAPAGAR)
                            .addComponent(jLabelNdC)
                            .addComponent(jLabelTotal)
                            .addComponent(jLabelNombredeC))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEfectivo)
                            .addComponent(jLabelMétodo)
                            .addComponent(jButtonTarjeta)
                            .addComponent(jButtonNequi))
                        .addGap(23, 23, 23)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelATAJOSTECLADO)
                    .addComponent(jLabelF1NuevaVenta)
                    .addComponent(jLabelF2BuscarProducto)
                    .addComponent(jLabelF3IngresarMerma)
                    .addComponent(jLabelF4CerrarCajaTurno))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



/**
 * Método corregido que busca el producto mapeando los campos exactos de tu base de datos
 */
    
    private void configurarLogicaVentas() {
    // 1. Configurar el modelo dinámico sobre tu jTableFactura existente
    modeloFactura = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Cód. Barras", "Corte de Carne", "Precio / KG", "Peso (KG)", "Subtotal"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };
    jTableFactura.setModel(modeloFactura);
    
    // 2. Limpiar placeholders visuales por defecto
    jLabelValor.setText("$ 0.00");
    jLabelTotal.setText("$ 0.00");
    jTextFieldPRECIOPORKILO.setEditable(false);
    
    // 3. Cargar el ComboBox de clientes de forma segura desde la Base de Datos
    cargarClientes();
    
    // 4. Configurar el nuevo ComboBox de productos como buscador interactivo
    jComboBoxPRODUCTOSELECCIONADO.setEditable(true); 
    configurarBuscadorProductos();
    
    // Calcular subtotal del corte e introducirlo a la JTable al presionar ENTER en Peso a Despachar
    jTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            agregarCorteALaFactura();
        }
    });
}

private void configurarBuscadorProductos() {
    jComboBoxPRODUCTOSELECCIONADO.removeAllItems();
    // Elemento por defecto para dejar la sección en blanco
    jComboBoxPRODUCTOSELECCIONADO.addItem("- Seleccione Producto -");
    
    // Cargar inicialmente todos los productos activos
    String sql = "SELECT nombre FROM productos WHERE estado = 'Activo' ORDER BY nombre ASC";
    try (Connection con = new conexion().conectar();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            jComboBoxPRODUCTOSELECCIONADO.addItem(rs.getString("nombre"));
        }
    } catch (SQLException e) {
        System.err.println("Error al cargar productos: " + e.getMessage());
    }

    // Configurar el autocompletado en tiempo real al escribir
    final javax.swing.JTextField tf = (javax.swing.JTextField) jComboBoxPRODUCTOSELECCIONADO.getEditor().getEditorComponent();
    tf.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent e) {
            if (e.getKeyCode() == java.awt.event.KeyEvent.VK_UP || 
                e.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN || 
                e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                return;
            }
            
            String texto = tf.getText().trim();
            jComboBoxPRODUCTOSELECCIONADO.removeAllItems();
            
            // Si está vacío o es el por defecto, mantener la opción base
            if (texto.isEmpty() || texto.equals("- Seleccione Producto -")) {
                jComboBoxPRODUCTOSELECCIONADO.addItem("- Seleccione Producto -");
            }
            
            String sqlFiltrar = "SELECT nombre FROM productos WHERE nombre LIKE ? AND estado = 'Activo' ORDER BY nombre ASC";
            try (Connection con = new conexion().conectar();
                 PreparedStatement ps = con.prepareStatement(sqlFiltrar)) {
                ps.setString(1, "%" + texto + "%");
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        jComboBoxPRODUCTOSELECCIONADO.addItem(rs.getString("nombre"));
                    }
                }
            } catch (SQLException ex) {
                System.err.println("Error al filtrar productos: " + ex.getMessage());
            }
            
            tf.setText(texto);
            jComboBoxPRODUCTOSELECCIONADO.showPopup();
        }
    });

    // Evento para detectar cuándo seleccionan un producto
    jComboBoxPRODUCTOSELECCIONADO.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cargarDatosProductoSeleccionado();
        }
    });
}

private void cargarDatosProductoSeleccionado() {
    if (jComboBoxPRODUCTOSELECCIONADO.getSelectedItem() == null) return;

    String productoSeleccionado = jComboBoxPRODUCTOSELECCIONADO.getSelectedItem().toString().trim();
    
    // Si se selecciona la opción por defecto, vaciar campos y salir
    if (productoSeleccionado.isEmpty() || productoSeleccionado.equals("- Seleccione Producto -")) {
        jTextFieldPRECIOPORKILO.setText("");
        codigoProductoActual = "";
        stockActualProducto = 0.0;
        return;
    }

    String sql = "SELECT codigo_barras, precio_kg, stock_kg FROM productos WHERE nombre = ? AND estado = 'Activo'";
    try (Connection con = new conexion().conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        
        ps.setString(1, productoSeleccionado);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                codigoProductoActual = rs.getString("codigo_barras");
                jTextFieldPRECIOPORKILO.setText(String.valueOf(rs.getDouble("precio_kg")));
                stockActualProducto = rs.getDouble("stock_kg");
            }
        }
    } catch (SQLException e) {
        System.err.println("Error al cargar datos del producto: " + e.getMessage());
    }
}

private void agregarCorteALaFactura() {
    String pesoStr = jTextFieldPeso.getText().trim();
    String precioStr = jTextFieldPRECIOPORKILO.getText().trim();
    
    // 1. Validar que haya una selección válida en el ComboBox
    if (jComboBoxPRODUCTOSELECCIONADO.getSelectedItem() == null) {
        return;
    }
    String producto = jComboBoxPRODUCTOSELECCIONADO.getSelectedItem().toString().trim();
    
    // CORRECCIÓN: Evitar que se agregue la fila por defecto a la factura
    if (producto.equals("- Seleccione Producto -") || producto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto válido.", "Báscula", JOptionPane.WARNING_MESSAGE);
        jComboBoxPRODUCTOSELECCIONADO.requestFocus();
        return;
    }
    
    // 2. Validar que los campos críticos no estén vacíos
    if (pesoStr.isEmpty() || codigoProductoActual.isEmpty() || precioStr.isEmpty()) {
        return;
    }
    
    try {
        double peso = Double.parseDouble(pesoStr);
        double precio = Double.parseDouble(precioStr);
        
        if (peso <= 0) {
            JOptionPane.showMessageDialog(this, "El peso ingresado debe ser mayor a 0.", "Báscula", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Regla de Negocio: Validar que no se venda más de lo disponible en vitrinas
        if (peso > stockActualProducto) {
            JOptionPane.showMessageDialog(this, "No hay suficiente stock en vitrina. Disponible: " + stockActualProducto + " KG", "Caja", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double subtotal = peso * precio;
        jLabelValor.setText("$ " + String.format("%.2f", subtotal));
        
        // 3. Si el producto ya se encuentra listado en el ticket, acumulamos los kilogramos despachados
        for (int i = 0; i < jTableFactura.getRowCount(); i++) {
            if (jTableFactura.getValueAt(i, 0).toString().equals(codigoProductoActual)) {
                double pesoExistente = (double) jTableFactura.getValueAt(i, 3);
                if ((pesoExistente + peso) > stockActualProducto) {
                    JOptionPane.showMessageDialog(this, "El peso acumulado excede las existencias del inventario.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                double nuevoSubtotal = (pesoExistente + peso) * precio;
                jTableFactura.setValueAt(pesoExistente + peso, i, 3);
                jTableFactura.setValueAt(nuevoSubtotal, i, 4);
                recalcularTotalFactura();
                limpiarSeccionBascula();
                return;
            }
        }
        
        // 4. Agregar nuevo renglón a la tabla usando la variable 'producto' obtenida del combo
        modeloFactura.addRow(new Object[]{codigoProductoActual, producto, precio, peso, subtotal});
        recalcularTotalFactura();
        limpiarSeccionBascula();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique el formato del peso ingresado.", "Error de conversión", JOptionPane.ERROR_MESSAGE);
    }
}

private void recalcularTotalFactura() {
    totalFactura = 0.0;
    for (int i = 0; i < modeloFactura.getRowCount(); i++) {
        totalFactura += (double) modeloFactura.getValueAt(i, 4);
    }
    jLabelTotal.setText("$ " + String.format("%.2f", totalFactura));
}

private void cargarClientes() {
    jComboBoxClienteCedula.removeAllItems();
    jComboBoxClienteCedula.addItem("000000"); // Opción rápida de caja por defecto
    jComboBoxClienteCedula.setEditable(true); // Permitir escribir para buscar

    // Cargar inicialmente todas las cédulas disponibles
    String sql = "SELECT cedula FROM clientes ORDER BY cedula ASC";
    try (Connection con = new conexion().conectar();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            jComboBoxClienteCedula.addItem(rs.getString("cedula"));
        }
    } catch (SQLException e) {
        System.err.println("No se pudo conectar a la tabla de clientes: " + e.getMessage());
    }

    // Configurar el autocompletado e interacción en tiempo real al escribir
    final javax.swing.JTextField tf = (javax.swing.JTextField) jComboBoxClienteCedula.getEditor().getEditorComponent();
    tf.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent e) {
            // Ignorar flechas de navegación y Enter
            if (e.getKeyCode() == java.awt.event.KeyEvent.VK_UP || 
                e.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN || 
                e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                return;
            }
            
            String texto = tf.getText().trim();
            jComboBoxClienteCedula.removeAllItems();
            
            // Si está vacío, reponer la opción genérica por defecto
            if (texto.isEmpty()) {
                jComboBoxClienteCedula.addItem("000000");
            }

            // Filtrar las cédulas que coincidan con lo que digita el cajero
            String sqlFiltrar = "SELECT cedula FROM clientes WHERE cedula LIKE ? ORDER BY cedula ASC";
            try (Connection con = new conexion().conectar();
                 PreparedStatement ps = con.prepareStatement(sqlFiltrar)) {
                ps.setString(1, "%" + texto + "%");
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        jComboBoxClienteCedula.addItem(rs.getString("cedula"));
                    }
                }
            } catch (SQLException ex) {
                System.err.println("Error al filtrar cédulas: " + ex.getMessage());
            }
            
            tf.setText(texto);
            jComboBoxClienteCedula.showPopup();
        }
    });

    // Evento para detectar cuándo cambian o seleccionan una cédula y mostrar el nombre
    jComboBoxClienteCedula.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            actualizarNombreCliente();
        }
    });
}

private void actualizarNombreCliente() {
    if (jComboBoxClienteCedula.getSelectedItem() == null) {
        jLabelNombredeC.setText("Cliente No Seleccionado");
        return;
    }

    String cedulaSeleccionada = jComboBoxClienteCedula.getSelectedItem().toString().trim();

    if (cedulaSeleccionada.equals("000000") || cedulaSeleccionada.isEmpty()) {
        jLabelNombredeC.setText("Cliente General");
        return;
    }

    String sql = "SELECT nombre FROM clientes WHERE cedula = ?";
    try (Connection con = new conexion().conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, cedulaSeleccionada);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                jLabelNombredeC.setText(rs.getString("nombre"));
            } else {
                // Si escribió una cédula que no existe aún en los registros
                jLabelNombredeC.setText("Cliente No Registrado");
            }
        }
    } catch (SQLException e) {
        System.err.println("Error al obtener nombre del cliente: " + e.getMessage());
        jLabelNombredeC.setText("Error al cargar");
    }
}

private int obtenerIdClientePorCedula() {
    if (jComboBoxClienteCedula.getSelectedItem() == null) return 1;
    
    String cedula = jComboBoxClienteCedula.getSelectedItem().toString().trim();
    if (cedula.equals("000000") || cedula.isEmpty()) return 1; // ID Genérico de control
    
    String sql = "SELECT id_cliente FROM clientes WHERE cedula = ?";
    try (Connection con = new conexion().conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, cedula);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) return rs.getInt("id_cliente");
        }
    } catch (SQLException e) {
        System.err.println("Error al obtener ID del cliente: " + e.getMessage());
    }
    return 1;
}

/**
 * Transacción ACID atómica que guarda cabecera, ítems detallados basados en la estructura real y actualiza stocks
 */
private void procesarPagoCompleto(String metodoPago) {
    if (jTableFactura.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "La factura actual no contiene ningún elemento.", "Caja Vacía", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int idCliente = obtenerIdClientePorCedula();
    int idUsuario = 1; // Ajustar dinámicamente según sesión iniciada
    
    Connection con = null;
    PreparedStatement psVenta = null;
    PreparedStatement psDetalle = null;
    PreparedStatement psStock = null;
    PreparedStatement psBuscarId = null; 
    
    try {
        con = new conexion().conectar();
        con.setAutoCommit(false); 
        
        // 1. Guardar Maestro de Venta
        String sqlVenta = "INSERT INTO ventas (id_cliente, id_usuario, fecha, total, metodo_pago) VALUES (?, ?, NOW(), ?, ?)";
        psVenta = con.prepareStatement(sqlVenta, Statement.RETURN_GENERATED_KEYS);
        psVenta.setInt(1, idCliente);
        psVenta.setInt(2, idUsuario);
        psVenta.setDouble(3, totalFactura);
        psVenta.setString(4, metodoPago);
        psVenta.executeUpdate();
        
        int idVenta = 1;
        try (ResultSet generatedKeys = psVenta.getGeneratedKeys()) {
            if (generatedKeys.next()) idVenta = generatedKeys.getInt(1);
        }
        
        // 2. Sentencias SQL adaptadas a la estructura real de tu BD
        String sqlBuscarId = "SELECT id_producto FROM productos WHERE codigo_barras = ?";
        String sqlDetalle = "INSERT INTO detalle_venta (id_venta, id_producto, peso_kg, precio_kg, subtotal) VALUES (?, ?, ?, ?, ?)";
        String sqlStock = "UPDATE productos SET stock_kg = stock_kg - ? WHERE codigo_barras = ?";
        
        psBuscarId = con.prepareStatement(sqlBuscarId);
        psDetalle = con.prepareStatement(sqlDetalle);
        psStock = con.prepareStatement(sqlStock);
        
        // 3. Procesar las filas del JTable
        for (int i = 0; i < jTableFactura.getRowCount(); i++) {
            String codBarras = jTableFactura.getValueAt(i, 0).toString();
            double precioKg = (double) jTableFactura.getValueAt(i, 2);
            double pesoKg = (double) jTableFactura.getValueAt(i, 3);
            double subtotal = (double) jTableFactura.getValueAt(i, 4);
            
            // Buscar id_producto numérico desde el código de barras asignado
            psBuscarId.setString(1, codBarras);
            int idProducto = 0;
            try (ResultSet rsId = psBuscarId.executeQuery()) {
                if (rsId.next()) {
                    idProducto = rsId.getInt("id_producto");
                } else {
                    throw new SQLException("No se encontró el ID interno para el producto: " + codBarras);
                }
            }
            
            // Parámetros de inserción detallada
            psDetalle.setInt(1, idVenta);
            psDetalle.setInt(2, idProducto);
            psDetalle.setDouble(3, pesoKg);
            psDetalle.setDouble(4, precioKg);
            psDetalle.setDouble(5, subtotal);
            psDetalle.addBatch();
            
            // Parámetros de actualización de inventarios
            psStock.setDouble(1, pesoKg);
            psStock.setString(2, codBarras);
            psStock.addBatch();
        }
        
        psDetalle.executeBatch();
        psStock.executeBatch();
        
        con.commit(); 
        JOptionPane.showMessageDialog(this, "¡Venta pagada con " + metodoPago + " exitosamente!", "Facturación", JOptionPane.INFORMATION_MESSAGE);
        limpiarFormularioCompleto();
        
    } catch (SQLException e) {
        if (con != null) {
            try { 
                con.rollback(); 
                System.out.println("Transacción deshacedora ejecutada correctamente.");
            } catch (SQLException ex) { 
                System.err.println("Error ejecutando rollback: " + ex.getMessage()); 
            }
        }
        JOptionPane.showMessageDialog(this, "Error procesando el cobro en el motor: " + e.getMessage(), "Error Transacción", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (psBuscarId != null) psBuscarId.close();
            if (psVenta != null) psVenta.close();
            if (psDetalle != null) psDetalle.close();
            if (psStock != null) psStock.close();
            if (con != null) con.close();
        } catch (SQLException e) { 
            System.err.println("Error al liberar recursos: " + e.getMessage()); 
        }
    }
}

private void limpiarSeccionBascula() {
    if (jComboBoxPRODUCTOSELECCIONADO.getItemCount() > 0) {
        jComboBoxPRODUCTOSELECCIONADO.setSelectedIndex(0); // Regresa a "- Seleccione Producto -"
    }
    jTextFieldPRECIOPORKILO.setText(""); 
    jTextFieldPeso.setText("");
    jLabelValor.setText("$ 0.00");
    codigoProductoActual = "";
    stockActualProducto = 0.0;
    
    jComboBoxPRODUCTOSELECCIONADO.requestFocus();
}

private void limpiarFormularioCompleto() {
    limpiarSeccionBascula();
    modeloFactura.setRowCount(0);
    jLabelTotal.setText("$ 0.00");
    totalFactura = 0.0;
    if (jComboBoxClienteCedula.getItemCount() > 0) {
        jComboBoxClienteCedula.setSelectedIndex(0);
    }
    jLabelNombredeC.setText("Cliente General");
}
    
    private void jTextFieldPRECIOPORKILOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPRECIOPORKILOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPRECIOPORKILOActionPerformed

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoActionPerformed

    private void jComboBoxClienteCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteCedulaActionPerformed

    private void jButtonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfectivoActionPerformed
  procesarPagoCompleto("Efectivo");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEfectivoActionPerformed

    private void jButtonComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprasActionPerformed

        FrmCompras form1 = new FrmCompras();
        jDesktopPane1.add(form1);
        form1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComprasActionPerformed

    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed

        FrmProductos form1 = new FrmProductos();
        jDesktopPane1.add(form1);
        form1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProductosActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        FrmClientes form1 = new FrmClientes();
        jDesktopPane1.add(form1);
        form1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        FrmUsuarios form1 = new FrmUsuarios();
        jDesktopPane1.add(form1);
        form1.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesiónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarSesiónActionPerformed

    private void jButtonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTarjetaActionPerformed

procesarPagoCompleto("Tarjeta");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTarjetaActionPerformed

    private void jButtonNequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNequiActionPerformed
   
procesarPagoCompleto("Nequi");        

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonNequiActionPerformed

    private void jButtonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriasActionPerformed
        FrmCategorias form1 = new FrmCategorias();
        jDesktopPane1.add(form1);
        form1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCategoriasActionPerformed

    private void jButtonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveedoresActionPerformed
    FrmProveedores form1 = new FrmProveedores();
        jDesktopPane1.add(form1);
        form1.setVisible(true);    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaGeneralPuntodeVentayPesajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCategorias;
    private javax.swing.JButton jButtonCerrarSesión;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonCompras;
    private javax.swing.JButton jButtonEfectivo;
    private javax.swing.JButton jButtonNequi;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonProveedores;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonTarjeta;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JComboBox<String> jComboBoxClienteCedula;
    private javax.swing.JComboBox<String> jComboBoxPRODUCTOSELECCIONADO;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelATAJOSTECLADO;
    private javax.swing.JLabel jLabelBÁSCULA;
    private javax.swing.JLabel jLabelClienteCedula;
    private javax.swing.JLabel jLabelDETALLEDELAFACTURAACTUAL;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelF1NuevaVenta;
    private javax.swing.JLabel jLabelF2BuscarProducto;
    private javax.swing.JLabel jLabelF3IngresarMerma;
    private javax.swing.JLabel jLabelF4CerrarCajaTurno;
    private javax.swing.JLabel jLabelMétodo;
    private javax.swing.JLabel jLabelNdC;
    private javax.swing.JLabel jLabelNombredeC;
    private javax.swing.JLabel jLabelPESOADESPACHAR;
    private javax.swing.JLabel jLabelPRECIOPORKILO;
    private javax.swing.JLabel jLabelPRODUCTOSELECCIONADO;
    private javax.swing.JLabel jLabelPÁGINADECIERREYMÉTODOSDEPAGO;
    private javax.swing.JLabel jLabelTOTALAPAGAR;
    private javax.swing.JLabel jLabelTextoCondiguracion;
    private javax.swing.JLabel jLabelTextomenu;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelVALORTOTALDELCORTE;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFactura;
    private javax.swing.JTextField jTextFieldPRECIOPORKILO;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
