/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author darie
 */
public class VistaGeneralPuntodeVentayPesajes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGeneralPuntodeVentayPesajes.class.getName());

    /**
     * Creates new form a
     */
    public VistaGeneralPuntodeVentayPesajes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelTextomenu = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelBÁSCULA = new javax.swing.JLabel();
        jLabelPRODUCTOSELECCIONADO = new javax.swing.JLabel();
        jLabelPRECIOPORKILO = new javax.swing.JLabel();
        jTextFieldPRECIOPORKILO = new javax.swing.JTextField();
        jTextFieldPRODUCTOSELECCIONADO = new javax.swing.JTextField();
        jLabelPESOADESPACHAR = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabelVALORTOTALDELCORTE = new javax.swing.JLabel();
        jLabelDETALLEDELAFACTURAACTUAL = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFactura = new javax.swing.JTable();
        jLabelPÁGINADECIERREYMÉTODOSDEPAGO = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabelCliente = new javax.swing.JLabel();
        jLabelATAJOSTECLADO = new javax.swing.JLabel();
        jButtonEfectivo = new javax.swing.JButton();
        jLabelF1NuevaVenta = new javax.swing.JLabel();
        jLabelF2BuscarProducto = new javax.swing.JLabel();
        jLabelEmpresa = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonVentas = new javax.swing.JButton();
        jButtonCompras = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jButtonMovimientos = new javax.swing.JButton();
        jButtonCategorias = new javax.swing.JButton();
        jButtonProveedores = new javax.swing.JButton();
        jButtonMermas = new javax.swing.JButton();
        jLabelTextoCondiguracion = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonCerrarSesión = new javax.swing.JButton();
        jLabelMétodo = new javax.swing.JLabel();
        jButtonTarjeta = new javax.swing.JButton();
        jLabelF3IngresarMerma = new javax.swing.JLabel();
        jButtonNequi = new javax.swing.JButton();
        jLabelF4CerrarCajaTurno = new javax.swing.JLabel();
        jLabelTOTALAPAGAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTextomenu.setText("MENÚ DE MÓDULOS");

        jLabelTotal.setText("$ 77.000");

        jLabelBÁSCULA.setText("BÁSCULA CALCULADORA");

        jLabelPRODUCTOSELECCIONADO.setText("PRODUCTO SELECCIONADO:");

        jLabelPRECIOPORKILO.setText("PRECIO POR KILO:");

        jTextFieldPRECIOPORKILO.addActionListener(this::jTextFieldPRECIOPORKILOActionPerformed);

        jTextFieldPRODUCTOSELECCIONADO.addActionListener(this::jTextFieldPRODUCTOSELECCIONADOActionPerformed);

        jLabelPESOADESPACHAR.setText("PESO A DESPACHAR");

        jTextFieldPeso.addActionListener(this::jTextFieldPesoActionPerformed);

        jLabelVALORTOTALDELCORTE.setText("VALOR TOTAL DEL CORTE:");

        jLabelDETALLEDELAFACTURAACTUAL.setText("DETALLE DE LA FACTURA ACTUAL");

        jLabelValor.setText("$ 50.000");

        jTableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cód. Barras", "Corte de Carne", "Precio / KG", "Peso (KG)", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTableFactura);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabelPÁGINADECIERREYMÉTODOSDEPAGO.setText("PÁGINA DE CIERRE Y MÉTODOS DE PAGO");

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCliente.addActionListener(this::jComboBoxClienteActionPerformed);

        jLabelCliente.setText("Cliente:");

        jLabelATAJOSTECLADO.setText("ATAJOS TECLADO:");

        jButtonEfectivo.setText("Efectivo");
        jButtonEfectivo.addActionListener(this::jButtonEfectivoActionPerformed);

        jLabelF1NuevaVenta.setText("F1: Nueva Venta");

        jLabelF2BuscarProducto.setText("F2: Buscar Producto");

        jLabelEmpresa.setText("[] SISTEMA CARNICERÍA \"EL CORTE\"");

        jToolBar1.setBackground(new java.awt.Color(153, 255, 153));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonVentas.setText("VENTAS");
        jButtonVentas.setFocusable(false);
        jButtonVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVentas.addActionListener(this::jButtonVentasActionPerformed);
        jToolBar1.add(jButtonVentas);

        jButtonCompras.setText("COMPRAS");
        jButtonCompras.setFocusable(false);
        jButtonCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCompras.addActionListener(this::jButtonComprasActionPerformed);
        jToolBar1.add(jButtonCompras);

        jButtonProductos.setText("PRODUCTOS");
        jButtonProductos.setFocusable(false);
        jButtonProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProductos.addActionListener(this::jButtonProductosActionPerformed);
        jToolBar1.add(jButtonProductos);

        jButtonMovimientos.setText("MOVIMIENTOS");
        jButtonMovimientos.setFocusable(false);
        jButtonMovimientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMovimientos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMovimientos.addActionListener(this::jButtonMovimientosActionPerformed);
        jToolBar1.add(jButtonMovimientos);

        jButtonCategorias.setText("Categorias");
        jButtonCategorias.setFocusable(false);
        jButtonCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCategorias.addActionListener(this::jButtonCategoriasActionPerformed);
        jToolBar1.add(jButtonCategorias);

        jButtonProveedores.setText("Proveedores");
        jButtonProveedores.setFocusable(false);
        jButtonProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProveedores.addActionListener(this::jButtonProveedoresActionPerformed);
        jToolBar1.add(jButtonProveedores);

        jButtonMermas.setText("MERMAS");
        jButtonMermas.setFocusable(false);
        jButtonMermas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMermas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMermas.addActionListener(this::jButtonMermasActionPerformed);
        jToolBar1.add(jButtonMermas);

        jLabelTextoCondiguracion.setText("CONFIGURACIÓN");
        jToolBar1.add(jLabelTextoCondiguracion);

        jButtonClientes.setText("Clientes");
        jButtonClientes.setFocusable(false);
        jButtonClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClientes.addActionListener(this::jButtonClientesActionPerformed);
        jToolBar1.add(jButtonClientes);

        jButtonUsuarios.setText("Usuarios");
        jButtonUsuarios.setFocusable(false);
        jButtonUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUsuarios.addActionListener(this::jButtonUsuariosActionPerformed);
        jToolBar1.add(jButtonUsuarios);

        jButtonReportes.setText("Reportes");
        jButtonReportes.setFocusable(false);
        jButtonReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReportes.addActionListener(this::jButtonReportesActionPerformed);
        jToolBar1.add(jButtonReportes);

        jButtonCerrarSesión.setText("Cerrar Sesión");
        jButtonCerrarSesión.setFocusable(false);
        jButtonCerrarSesión.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCerrarSesión.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCerrarSesión.addActionListener(this::jButtonCerrarSesiónActionPerformed);
        jToolBar1.add(jButtonCerrarSesión);

        jLabelMétodo.setText("Método:");

        jButtonTarjeta.setText("Tarjeta");
        jButtonTarjeta.addActionListener(this::jButtonTarjetaActionPerformed);

        jLabelF3IngresarMerma.setText("F3: Ingresar Merma");

        jButtonNequi.setText("Nequi");
        jButtonNequi.addActionListener(this::jButtonNequiActionPerformed);

        jLabelF4CerrarCajaTurno.setText("F4: Cerrar Caja / Turno");

        jLabelTOTALAPAGAR.setText("TOTAL A PAGAR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabelTextomenu)))
                            .addComponent(jLabelATAJOSTECLADO))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCliente)
                                            .addComponent(jLabelMétodo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonEfectivo)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonTarjeta)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonNequi))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelF1NuevaVenta)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelF2BuscarProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelF3IngresarMerma)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelTOTALAPAGAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelF4CerrarCajaTurno))))
                            .addComponent(jLabelPÁGINADECIERREYMÉTODOSDEPAGO)
                            .addComponent(jLabelBÁSCULA)
                            .addComponent(jLabelDETALLEDELAFACTURAACTUAL)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPRECIOPORKILO)
                                            .addComponent(jLabelPRODUCTOSELECCIONADO))
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelPESOADESPACHAR))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPRECIOPORKILO, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPRODUCTOSELECCIONADO))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelVALORTOTALDELCORTE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelEmpresa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextomenu)
                    .addComponent(jLabelBÁSCULA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPRODUCTOSELECCIONADO)
                            .addComponent(jTextFieldPRODUCTOSELECCIONADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPRECIOPORKILO)
                            .addComponent(jTextFieldPRECIOPORKILO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPESOADESPACHAR)
                            .addComponent(jLabelVALORTOTALDELCORTE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValor))
                        .addGap(47, 47, 47)
                        .addComponent(jLabelDETALLEDELAFACTURAACTUAL)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPÁGINADECIERREYMÉTODOSDEPAGO)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTOTALAPAGAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTarjeta)
                        .addComponent(jButtonNequi)
                        .addComponent(jLabelTotal))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMétodo)
                        .addComponent(jButtonEfectivo)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelATAJOSTECLADO)
                    .addComponent(jLabelF1NuevaVenta)
                    .addComponent(jLabelF2BuscarProducto)
                    .addComponent(jLabelF3IngresarMerma)
                    .addComponent(jLabelF4CerrarCajaTurno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPRECIOPORKILOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPRECIOPORKILOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPRECIOPORKILOActionPerformed

    private void jTextFieldPRODUCTOSELECCIONADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPRODUCTOSELECCIONADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPRODUCTOSELECCIONADOActionPerformed

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jButtonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEfectivoActionPerformed

    private void jButtonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVentasActionPerformed

    private void jButtonComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComprasActionPerformed

    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProductosActionPerformed

    private void jButtonMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMovimientosActionPerformed

    private void jButtonMermasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMermasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMermasActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        FrmClientes form1 = new FrmClientes();
        jDesktopPane1.add(form1);
        form1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        FmrUsuarios form1 = new FmrUsuarios();
        jDesktopPane1.add(form1);
        form1.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesiónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarSesiónActionPerformed

    private void jButtonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTarjetaActionPerformed

    private void jButtonNequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNequiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNequiActionPerformed

    private void jButtonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriasActionPerformed
        FrmCategorias form1 = new FrmCategorias();
        jDesktopPane1.add(form1);
        form1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCategoriasActionPerformed

    private void jButtonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveedoresActionPerformed
    FrmProveedores form1 = new FrmProveedores();
        jDesktopPane1.add(form1);
        form1.setVisible(true);    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaGeneralPuntodeVentayPesajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCategorias;
    private javax.swing.JButton jButtonCerrarSesión;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonCompras;
    private javax.swing.JButton jButtonEfectivo;
    private javax.swing.JButton jButtonMermas;
    private javax.swing.JButton jButtonMovimientos;
    private javax.swing.JButton jButtonNequi;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonProveedores;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonTarjeta;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JButton jButtonVentas;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelATAJOSTECLADO;
    private javax.swing.JLabel jLabelBÁSCULA;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelDETALLEDELAFACTURAACTUAL;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelF1NuevaVenta;
    private javax.swing.JLabel jLabelF2BuscarProducto;
    private javax.swing.JLabel jLabelF3IngresarMerma;
    private javax.swing.JLabel jLabelF4CerrarCajaTurno;
    private javax.swing.JLabel jLabelMétodo;
    private javax.swing.JLabel jLabelPESOADESPACHAR;
    private javax.swing.JLabel jLabelPRECIOPORKILO;
    private javax.swing.JLabel jLabelPRODUCTOSELECCIONADO;
    private javax.swing.JLabel jLabelPÁGINADECIERREYMÉTODOSDEPAGO;
    private javax.swing.JLabel jLabelTOTALAPAGAR;
    private javax.swing.JLabel jLabelTextoCondiguracion;
    private javax.swing.JLabel jLabelTextomenu;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelVALORTOTALDELCORTE;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFactura;
    private javax.swing.JTextField jTextFieldPRECIOPORKILO;
    private javax.swing.JTextField jTextFieldPRODUCTOSELECCIONADO;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
