/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darie
 */
public class VistaGeneralPuntodeVentayPesajes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGeneralPuntodeVentayPesajes.class.getName());

    
        // Variables lógicas añadidas para el control de la caja de la carnicería
    private DefaultTableModel modeloFactura;
    private double totalFactura = 0.0;
    private double stockActualProducto = 0.0;
    private String codigoProductoActual = "";
    
    /**
     * Creates new form a
     */
    public VistaGeneralPuntodeVentayPesajes() {
        initComponents();
        configurarLogicaVentas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelTextomenu = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelBÁSCULA = new javax.swing.JLabel();
        jLabelPRODUCTOSELECCIONADO = new javax.swing.JLabel();
        jLabelPRECIOPORKILO = new javax.swing.JLabel();
        jTextFieldPRECIOPORKILO = new javax.swing.JTextField();
        jTextFieldPRODUCTOSELECCIONADO = new javax.swing.JTextField();
        jLabelPESOADESPACHAR = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabelVALORTOTALDELCORTE = new javax.swing.JLabel();
        jLabelDETALLEDELAFACTURAACTUAL = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFactura = new javax.swing.JTable();
        jLabelPÁGINADECIERREYMÉTODOSDEPAGO = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabelCliente = new javax.swing.JLabel();
        jLabelATAJOSTECLADO = new javax.swing.JLabel();
        jButtonEfectivo = new javax.swing.JButton();
        jLabelF1NuevaVenta = new javax.swing.JLabel();
        jLabelF2BuscarProducto = new javax.swing.JLabel();
        jLabelEmpresa = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCompras = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jButtonCategorias = new javax.swing.JButton();
        jButtonProveedores = new javax.swing.JButton();
        jLabelTextoCondiguracion = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonCerrarSesión = new javax.swing.JButton();
        jLabelMétodo = new javax.swing.JLabel();
        jButtonTarjeta = new javax.swing.JButton();
        jLabelF3IngresarMerma = new javax.swing.JLabel();
        jButtonNequi = new javax.swing.JButton();
        jLabelF4CerrarCajaTurno = new javax.swing.JLabel();
        jLabelTOTALAPAGAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTextomenu.setText("MENÚ DE MÓDULOS");

        jLabelTotal.setText("$ 77.000");

        jLabelBÁSCULA.setText("BÁSCULA CALCULADORA");

        jLabelPRODUCTOSELECCIONADO.setText("PRODUCTO SELECCIONADO:");

        jLabelPRECIOPORKILO.setText("PRECIO POR KILO:");

        jTextFieldPRECIOPORKILO.addActionListener(this::jTextFieldPRECIOPORKILOActionPerformed);

        jTextFieldPRODUCTOSELECCIONADO.addActionListener(this::jTextFieldPRODUCTOSELECCIONADOActionPerformed);

        jLabelPESOADESPACHAR.setText("PESO A DESPACHAR");

        jTextFieldPeso.addActionListener(this::jTextFieldPesoActionPerformed);

        jLabelVALORTOTALDELCORTE.setText("VALOR TOTAL DEL CORTE:");

        jLabelDETALLEDELAFACTURAACTUAL.setText("DETALLE DE LA FACTURA ACTUAL");

        jLabelValor.setText("$ 50.000");

        jTableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cód. Barras", "Corte de Carne", "Precio / KG", "Peso (KG)", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTableFactura);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabelPÁGINADECIERREYMÉTODOSDEPAGO.setText("PÁGINA DE CIERRE Y MÉTODOS DE PAGO");

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCliente.addActionListener(this::jComboBoxClienteActionPerformed);

        jLabelCliente.setText("Cliente:");

        jLabelATAJOSTECLADO.setText("ATAJOS TECLADO:");

        jButtonEfectivo.setText("Efectivo");
        jButtonEfectivo.addActionListener(this::jButtonEfectivoActionPerformed);

        jLabelF1NuevaVenta.setText("F1: Nueva Venta");

        jLabelF2BuscarProducto.setText("F2: Buscar Producto");

        jLabelEmpresa.setText("[] SISTEMA CARNICERÍA \"EL CORTE\"");

        jToolBar1.setBackground(new java.awt.Color(153, 255, 153));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonCompras.setText("Compras");
        jButtonCompras.setFocusable(false);
        jButtonCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCompras.addActionListener(this::jButtonComprasActionPerformed);
        jToolBar1.add(jButtonCompras);

        jButtonProductos.setText("Productos");
        jButtonProductos.setFocusable(false);
        jButtonProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProductos.addActionListener(this::jButtonProductosActionPerformed);
        jToolBar1.add(jButtonProductos);

        jButtonCategorias.setText("Categorias");
        jButtonCategorias.setFocusable(false);
        jButtonCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCategorias.addActionListener(this::jButtonCategoriasActionPerformed);
        jToolBar1.add(jButtonCategorias);

        jButtonProveedores.setText("Proveedores");
        jButtonProveedores.setFocusable(false);
        jButtonProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProveedores.addActionListener(this::jButtonProveedoresActionPerformed);
        jToolBar1.add(jButtonProveedores);

        jLabelTextoCondiguracion.setText("CONFIGURACIÓN");
        jToolBar1.add(jLabelTextoCondiguracion);

        jButtonClientes.setText("Clientes");
        jButtonClientes.setFocusable(false);
        jButtonClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClientes.addActionListener(this::jButtonClientesActionPerformed);
        jToolBar1.add(jButtonClientes);

        jButtonUsuarios.setText("Usuarios");
        jButtonUsuarios.setFocusable(false);
        jButtonUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUsuarios.addActionListener(this::jButtonUsuariosActionPerformed);
        jToolBar1.add(jButtonUsuarios);

        jButtonReportes.setText("Reportes");
        jButtonReportes.setFocusable(false);
        jButtonReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReportes.addActionListener(this::jButtonReportesActionPerformed);
        jToolBar1.add(jButtonReportes);

        jButtonCerrarSesión.setText("Cerrar Sesión");
        jButtonCerrarSesión.setFocusable(false);
        jButtonCerrarSesión.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCerrarSesión.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCerrarSesión.addActionListener(this::jButtonCerrarSesiónActionPerformed);
        jToolBar1.add(jButtonCerrarSesión);

        jLabelMétodo.setText("Método:");

        jButtonTarjeta.setText("Tarjeta");
        jButtonTarjeta.addActionListener(this::jButtonTarjetaActionPerformed);

        jLabelF3IngresarMerma.setText("F3: Ingresar Merma");

        jButtonNequi.setText("Nequi");
        jButtonNequi.addActionListener(this::jButtonNequiActionPerformed);

        jLabelF4CerrarCajaTurno.setText("F4: Cerrar Caja / Turno");

        jLabelTOTALAPAGAR.setText("TOTAL A PAGAR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabelTextomenu)))
                            .addComponent(jLabelATAJOSTECLADO))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCliente)
                                            .addComponent(jLabelMétodo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonEfectivo)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonTarjeta)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonNequi))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelF1NuevaVenta)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelF2BuscarProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelF3IngresarMerma)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelTOTALAPAGAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelF4CerrarCajaTurno))))
                            .addComponent(jLabelPÁGINADECIERREYMÉTODOSDEPAGO)
                            .addComponent(jLabelBÁSCULA)
                            .addComponent(jLabelDETALLEDELAFACTURAACTUAL)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPRECIOPORKILO)
                                            .addComponent(jLabelPRODUCTOSELECCIONADO))
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelPESOADESPACHAR))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPRECIOPORKILO, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPRODUCTOSELECCIONADO))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelVALORTOTALDELCORTE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelEmpresa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextomenu)
                    .addComponent(jLabelBÁSCULA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPRODUCTOSELECCIONADO)
                            .addComponent(jTextFieldPRODUCTOSELECCIONADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPRECIOPORKILO)
                            .addComponent(jTextFieldPRECIOPORKILO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPESOADESPACHAR)
                            .addComponent(jLabelVALORTOTALDELCORTE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValor))
                        .addGap(47, 47, 47)
                        .addComponent(jLabelDETALLEDELAFACTURAACTUAL)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPÁGINADECIERREYMÉTODOSDEPAGO)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTOTALAPAGAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTarjeta)
                        .addComponent(jButtonNequi)
                        .addComponent(jLabelTotal))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMétodo)
                        .addComponent(jButtonEfectivo)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelATAJOSTECLADO)
                    .addComponent(jLabelF1NuevaVenta)
                    .addComponent(jLabelF2BuscarProducto)
                    .addComponent(jLabelF3IngresarMerma)
                    .addComponent(jLabelF4CerrarCajaTurno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void configurarLogicaVentas() {
        // 1. Configurar el modelo dinámico sobre tu jTableFactura existente
        modeloFactura = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Cód. Barras", "Corte de Carne", "Precio / KG", "Peso (KG)", "Subtotal"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquear edición directa en celdas
            }
        };
        jTableFactura.setModel(modeloFactura);
        
        // 2. Limpiar placeholders visuales por defecto
        jLabelValor.setText("$ 0.00");
        jLabelTotal.setText("$ 0.00");
        jTextFieldPRODUCTOSELECCIONADO.setEditable(false);
        jTextFieldPRECIOPORKILO.setEditable(false);
        
        // 3. Cargar el ComboBox de clientes de forma segura desde la Base de Datos
        cargarClientes();
        
        // 4. Configurar eventos de interacción para el pesaje instantáneo
        // Buscar producto cuando el operario escanee/digite y presione ENTER en el primer campo
        jTextFieldPRODUCTOSELECCIONADO.setEditable(true); // Permitir que use este campo para escanear código
        jTextFieldPRODUCTOSELECCIONADO.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductoPorCodigo();
            }
        });
        
        // Calcular subtotal del corte e introducirlo a la JTable al presionar ENTER en Peso a Despachar
        jTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCorteALaFactura();
            }
        });
    }
    
    /**
     * Método corregido que soluciona el error de la columna c.nombre usando c.nombre_categoria
     */
    private void buscarProductoPorCodigo() {
        String codigo = jTextFieldPRODUCTOSELECCIONADO.getText().trim();
        if (codigo.isEmpty()) return;
        
        // SOLUCIÓN AL ERROR DE COLUMNA: Aquí mapeamos exactamente tus campos reales
        String sql = "SELECT p.codigo_barras, p.nombre, p.precio_kg, p.stock_kg " +
                     "FROM productos p " +
                     "INNER JOIN categorias c ON p.id_categoria = c.id_categoria " +
                     "WHERE p.codigo_barras = ? AND p.estado = 'Activo'";
                     
        try (Connection con = new conexion().conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            ps.setString(1, codigo);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    codigoProductoActual = rs.getString("p.codigo_barras");
                    jTextFieldPRODUCTOSELECCIONADO.setText(rs.getString("p.nombre"));
                    jTextFieldPRECIOPORKILO.setText(String.valueOf(rs.getDouble("p.precio_kg")));
                    stockActualProducto = rs.getDouble("p.stock_kg");
                    
                    // Foco automático al peso para agilizar la cola de clientes
                    jTextFieldPeso.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "El producto no existe o está inactivo.", "Inventario", JOptionPane.WARNING_MESSAGE);
                    limpiarSeccionBascula();
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void agregarCorteALaFactura() {
        String pesoStr = jTextFieldPeso.getText().trim();
        String precioStr = jTextFieldPRECIOPORKILO.getText().trim();
        String producto = jTextFieldPRODUCTOSELECCIONADO.getText().trim();
        
        if (pesoStr.isEmpty() || codigoProductoActual.isEmpty() || precioStr.isEmpty()) {
            return;
        }
        
        try {
            double peso = Double.parseDouble(pesoStr);
            double precio = Double.parseDouble(precioStr);
            
            if (peso <= 0) {
                JOptionPane.showMessageDialog(this, "El peso ingresado debe ser mayor a 0.", "Báscula", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Regla de Negocio: Validar que no se venda más de lo disponible en vitrinas
            if (peso > stockActualProducto) {
                JOptionPane.showMessageDialog(this, "No hay suficiente stock en vitrina. Disponible: " + stockActualProducto + " KG", "Caja", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            double subtotal = peso * precio;
            jLabelValor.setText("$ " + String.format("%.2f", subtotal));
            
            // Si el producto ya se encuentra listado en el ticket, acumulamos los kilogramos despachados
            for (int i = 0; i < jTableFactura.getRowCount(); i++) {
                if (jTableFactura.getValueAt(i, 0).toString().equals(codigoProductoActual)) {
                    double pesoExistente = (double) jTableFactura.getValueAt(i, 3);
                    if ((pesoExistente + peso) > stockActualProducto) {
                        JOptionPane.showMessageDialog(this, "El peso acumulado excede las existencias del inventario.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    double nuevoSubtotal = (pesoExistente + peso) * precio;
                    jTableFactura.setValueAt(pesoExistente + peso, i, 3);
                    jTableFactura.setValueAt(nuevoSubtotal, i, 4);
                    recalcularTotalFactura();
                    limpiarSeccionBascula();
                    return;
                }
            }
            
            // Agregar nuevo renglón
            modeloFactura.addRow(new Object[]{codigoProductoActual, producto, precio, peso, subtotal});
            recalcularTotalFactura();
            limpiarSeccionBascula();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifique el formato del peso ingresado.", "Error de conversión", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void recalcularTotalFactura() {
        totalFactura = 0.0;
        for (int i = 0; i < modeloFactura.getRowCount(); i++) {
            totalFactura += (double) modeloFactura.getValueAt(i, 4);
        }
        jLabelTotal.setText("$ " + String.format("%.2f", totalFactura));
    }
    
    private void cargarClientes() {
        jComboBoxCliente.removeAllItems();
        jComboBoxCliente.addItem("000000 - Cliente General"); // Opción rápida de caja por defecto
        
        String sql = "SELECT cedula, nombre FROM clientes ORDER BY nombre ASC";
        try (Connection con = new conexion().conectar();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                jComboBoxCliente.addItem(rs.getString("cedula") + " - " + rs.getString("nombre"));
            }
        } catch (SQLException e) {
            System.err.println("No se pudo conectar a la tabla de clientes: " + e.getMessage());
        }
    }
    
    private int obtenerIdClientePorCedula() {
        String comboVal = jComboBoxCliente.getSelectedItem() != null ? jComboBoxCliente.getSelectedItem().toString() : "000000";
        if (comboVal.startsWith("000000")) return 1; // ID Genérico o por defecto en la BD
        
        String cedula = comboVal.split(" - ")[0].trim();
        String sql = "SELECT id_cliente FROM clientes WHERE cedula = ?";
        try (Connection con = new conexion().conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, cedula);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return rs.getInt("id_cliente");
            }
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
        return 1;
    }
    
    /**
     * Transacción ACID atómica que unifica la cabecera, los ítems vendidos y descuenta existencias
     */
    private void procesarPagoCompleto(String metodoPago) {
        if (jTableFactura.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "La factura actual no contiene ningún elemento.", "Caja Vacía", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idCliente = obtenerIdClientePorCedula();
        int idUsuario = 1; // Ajustar dinámicamente según sesión iniciada
        
        Connection con = null;
        PreparedStatement psVenta = null;
        PreparedStatement psDetalle = null;
        PreparedStatement psStock = null;
        
        try {
            con = new conexion().conectar();
            con.setAutoCommit(false); // Evita escrituras incompletas si hay cortes de luz o fallos
            
            // 1. Guardar Maestro de Venta incluyendo el método de pago elegido por botón
            String sqlVenta = "INSERT INTO ventas (id_cliente, id_usuario, fecha, total, metodo_pago) VALUES (?, ?, NOW(), ?, ?)";
            psVenta = con.prepareStatement(sqlVenta, Statement.RETURN_GENERATED_KEYS);
            psVenta.setInt(1, idCliente);
            psVenta.setInt(2, idUsuario);
            psVenta.setDouble(3, totalFactura);
            psVenta.setString(4, metodoPago);
            psVenta.executeUpdate();
            
            int idVenta = 1;
            try (ResultSet generatedKeys = psVenta.getGeneratedKeys()) {
                if (generatedKeys.next()) idVenta = generatedKeys.getInt(1);
            }
            
            // 2. Procesar inserciones en lote y actualización física de stock en KG
            String sqlDetalle = "INSERT INTO detalle_ventas (id_venta, codigo_barras, cantidad_kg, precio_venta) VALUES (?, ?, ?, ?)";
            String sqlStock = "UPDATE productos SET stock_kg = stock_kg - ? WHERE codigo_barras = ?";
            
            psDetalle = con.prepareStatement(sqlDetalle);
            psStock = con.prepareStatement(sqlStock);
            
            for (int i = 0; i < jTableFactura.getRowCount(); i++) {
                String cod = jTableFactura.getValueAt(i, 0).toString();
                double peso = (double) jTableFactura.getValueAt(i, 3);
                double prec = (double) jTableFactura.getValueAt(i, 2);
                
                psDetalle.setInt(1, idVenta);
                psDetalle.setString(2, cod);
                psDetalle.setDouble(3, peso);
                psDetalle.setDouble(4, prec);
                psDetalle.addBatch();
                
                psStock.setDouble(1, peso);
                psStock.setString(2, cod);
                psStock.addBatch();
            }
            
            psDetalle.executeBatch();
            psStock.executeBatch();
            
            con.commit(); // Confirmación exitosa en bloque
            JOptionPane.showMessageDialog(this, "¡Venta pagada con " + metodoPago + " exitosamente!", "Facturación", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormularioCompleto();
            
        } catch (SQLException e) {
            if (con != null) {
                try { con.rollback(); } catch (SQLException ex) { logger.severe(ex.getMessage()); }
            }
            JOptionPane.showMessageDialog(this, "Error procesando el cobro en el motor: " + e.getMessage(), "Error Transacción", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (psVenta != null) psVenta.close();
                if (psDetalle != null) psDetalle.close();
                if (psStock != null) psStock.close();
                if (con != null) con.close();
            } catch (SQLException e) { logger.severe(e.getMessage()); }
        }
    }
    
    private void limpiarSeccionBascula() {
        jTextFieldPRODUCTOSELECCIONADO.setText("");
        jTextFieldPRECIOPORKILO.setText("");
        jTextFieldPeso.setText("");
        jLabelValor.setText("$ 0.00");
        codigoProductoActual = "";
        stockActualProducto = 0.0;
        jTextFieldPRODUCTOSELECCIONADO.requestFocus();
    }
    
    private void limpiarFormularioCompleto() {
        limpiarSeccionBascula();
        modeloFactura.setRowCount(0);
        jLabelTotal.setText("$ 0.00");
        totalFactura = 0.0;
        if (jComboBoxCliente.getItemCount() > 0) jComboBoxCliente.setSelectedIndex(0);
    }
    
    private void jTextFieldPRECIOPORKILOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPRECIOPORKILOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPRECIOPORKILOActionPerformed

    private void jTextFieldPRODUCTOSELECCIONADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPRODUCTOSELECCIONADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPRODUCTOSELECCIONADOActionPerformed

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jButtonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfectivoActionPerformed
  procesarPagoCompleto("Efectivo");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEfectivoActionPerformed

    private void jButtonComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprasActionPerformed

        FrmCompras form1 = new FrmCompras();
        jDesktopPane1.add(form1);
        form1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComprasActionPerformed

    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed

        FrmProductos form1 = new FrmProductos();
        jDesktopPane1.add(form1);
        form1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProductosActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        FrmClientes form1 = new FrmClientes();
        jDesktopPane1.add(form1);
        form1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        FrmUsuarios form1 = new FrmUsuarios();
        jDesktopPane1.add(form1);
        form1.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesiónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarSesiónActionPerformed

    private void jButtonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTarjetaActionPerformed

procesarPagoCompleto("Tarjeta");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTarjetaActionPerformed

    private void jButtonNequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNequiActionPerformed
   
procesarPagoCompleto("Nequi");        

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonNequiActionPerformed

    private void jButtonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriasActionPerformed
        FrmCategorias form1 = new FrmCategorias();
        jDesktopPane1.add(form1);
        form1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCategoriasActionPerformed

    private void jButtonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveedoresActionPerformed
    FrmProveedores form1 = new FrmProveedores();
        jDesktopPane1.add(form1);
        form1.setVisible(true);    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaGeneralPuntodeVentayPesajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCategorias;
    private javax.swing.JButton jButtonCerrarSesión;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonCompras;
    private javax.swing.JButton jButtonEfectivo;
    private javax.swing.JButton jButtonNequi;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonProveedores;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonTarjeta;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelATAJOSTECLADO;
    private javax.swing.JLabel jLabelBÁSCULA;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelDETALLEDELAFACTURAACTUAL;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelF1NuevaVenta;
    private javax.swing.JLabel jLabelF2BuscarProducto;
    private javax.swing.JLabel jLabelF3IngresarMerma;
    private javax.swing.JLabel jLabelF4CerrarCajaTurno;
    private javax.swing.JLabel jLabelMétodo;
    private javax.swing.JLabel jLabelPESOADESPACHAR;
    private javax.swing.JLabel jLabelPRECIOPORKILO;
    private javax.swing.JLabel jLabelPRODUCTOSELECCIONADO;
    private javax.swing.JLabel jLabelPÁGINADECIERREYMÉTODOSDEPAGO;
    private javax.swing.JLabel jLabelTOTALAPAGAR;
    private javax.swing.JLabel jLabelTextoCondiguracion;
    private javax.swing.JLabel jLabelTextomenu;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelVALORTOTALDELCORTE;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFactura;
    private javax.swing.JTextField jTextFieldPRECIOPORKILO;
    private javax.swing.JTextField jTextFieldPRODUCTOSELECCIONADO;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
